#+TITLE: Build GARFIELD with waf

The [[http://garfield.web.cern.ch/garfield/][Garfield simulation of gaseous detectors]] is built with an archaic
set of tools, CERNLIB and a lot of added chaos.  This package tries to
automate the building.  It includes a copy of the GARFIELD FORTRAN
files and will download the neBEM code.

* Installation

A simple shell script that downloads everything, applies a coupld of
patches and exercises the native installation:

#+BEGIN_EXAMPLE
$ ./native.sh path/to/build/tmp
#+END_EXAMPLE

It requires that =pkg-config= can find GSL and the =cernlib= and
=ypatchy= are in your =$PATH=.

** RACF

When building on RACF you can satisfy the prerequisites by running the script through the provided [[./racf.sh]]:

#+BEGIN_EXAMPLE
$ ./racf.sh ./native.sh path/to/build/tmp
#+END_EXAMPLE

* Waf-based

General:

#+BEGIN_EXAMPLE
$ git clone https://github.com/brettviren/garfield-build.git
$ cd garfield-build/
$ waf --version  # one time unpacking of waf
$ waf configure build
#+END_EXAMPLE

On BNL's RACF, for now, one can build it by leveraging CERNLIB and GSL
installed in various places using the provided =racf.sh" script.
Clone as above and do:

#+begin_example
$ git clone https://github.com/brettviren/garfield-build.git
$ cd garfield-build/
$ ./racf.sh waf --version  # one time unpacking of waf
$ ./racf.sh waf configure build
$ ./racf.sh garfield-9
#+end_example
