CDECK  ID>, GINSK.
      SUBROUTINE GINSK(KWKID,LCDNR,ITR,N,PX,PY,IPET,XMIN,XMAX,
     + YMIN,YMAX,LENBUF,LDR,DATREC)
      CHARACTER*80 DATREC(LDR)
      DIMENSION PX(N),PY(N)
      RETURN
      END
