CDECK  ID>, OUTPUT2.
       SUBROUTINE OUTPUT2
*-----------------------------------------------------------------------
*   OUTPUT2 - Output after refining for high fields.
*   Author: Steve Biagi, with minor modifications.
*   (Last changed on  2/ 3/08.)
*-----------------------------------------------------------------------
       implicit none
*   Array dimensions.
       integer mxngas
       parameter(mxngas=6)
       INTEGER NGAS,NSTEP,IDBG
       DOUBLE PRECISION EFINAL,ESTEP,AKT,ARY,TEMPC,TORR
       PARAMETER(ARY=13.60569172)
       COMMON/INPT/NGAS,NSTEP,EFINAL,ESTEP,AKT,TEMPC,TORR,IDBG
*   Grouped QIN1 ... QIN6 in QINN
       DOUBLE PRECISION QELM,QSUM,QION,QINN,QSATT
       COMMON /MIX1/ QELM(2048),QSUM(2048),QION(mxngas,2048),
     -      QINn(220,2048,mxngas),QSATT(2048)
*   EVECT is originally called E or ES depending on the routine.
       DOUBLE PRECISION Evect,EROOT,QTOT,QREL,QINEL,QEL
       COMMON /MIX2/ Evect(2048),EROOT(2048),QTOT(2048),QREL(2048),
     -      QINEL(2048),QEL(2048)
*   Extensively reduced.
       INTEGER NINn
*           ,LION,LIN1,LIN2,LIN3,LIN4,LIN5,LIN6
*           DOUBLE PRECISION ALION,ALIN1,ALIN2,ALIN3,ALIN4,ALIN5,ALIN6
       COMMON /MIX3/ NINn(mxngas)
*           ,LION(6),LIN1(220),
*     -      LIN2(220),LIN3(220),LIN4(220),LIN5(220),LIN6(220),ALION(6),
*     -      ALIN1(220),ALIN2(220),ALIN3(220),ALIN4(220),ALIN5(220),
*     -      ALIN6(220)
*   Grouped AN1 ... AN6 in ANn
       DOUBLE PRECISION ANn,AN,FRAC
       COMMON /RATIO/ ANn(mxngas),AN,FRAC(mxngas)
       DOUBLE PRECISION TMAX,SMALL,API,ESTART,THETA,PHI,TCFMAX,RSTART,
     -      EMAG
       INTEGER NMAX
       COMMON/SETP/TMAX,SMALL,API,ESTART,THETA,PHI,TCFMAX(8),RSTART,
     -      EMAG,NMAX
*   Sometimes IPLAST is called LAST
       DOUBLE PRECISION CF,EIN,TCF,RGAS,WPL
       INTEGER IARRY,IPN,IPLAST,ISIZE
       COMMON/LARGE/CF(2048,512),EIN(512),TCF(2048),IARRY(512),
     -      RGAS(512),IPN(512),WPL(512),IPLAST,ISIZE
*   Adjusted size of ICOLL
       DOUBLE PRECISION TIME,SPEC,TMAX1,AVE,DEN,XID,X,Y,Z,ST
       INTEGER ICOLL,NNULL,ICOLN
       COMMON/OUTPT/TIME(300),ICOLL(5*mxngas),SPEC(2048),TMAX1,
     -      AVE,DEN,XID,X,Y,Z,ST,NNULL,ICOLN(512)
       DOUBLE PRECISION ZTOT,TTOT,ZTOTS,TTOTS
       COMMON/TTRM/ZTOT,TTOT,ZTOTS,TTOTS
       DOUBLE PRECISION SIMF
       COMMON/SINT/SIMF(2048)
*   Changed name of common from /NAMES/ to /MBGNAM/ for Mac OS X
       CHARACTER*15 NAMEG
       COMMON /MBGNAM/ NAMEG(mxngas)
       CHARACTER*30 DSCRPT
       COMMON/SCRIP/DSCRPT(512)
*-----------------------------------------------------------------------
*   MAGPAR - Interface parameters for gas mixing with Magboltz.
*   (Last changed on  2/ 3/08.)
*-----------------------------------------------------------------------
       INTEGER MXGNAM
       PARAMETER(MXGNAM=60)
       DOUBLE PRECISION FRAMIX
       LOGICAL LF0PLT,LCSPLT,LGKEEP,LBMCPR
       COMMON /MAGPAR/ FRAMIX(MXGNAM),LF0PLT,LCSPLT,LGKEEP,LBMCPR
       LOGICAL         LINPUT,LCELPR,LCELPL,LWRMRK,LISOCL,LCHGCH,
     -         LDRPLT,LDRPRT,LCLPRT,LCLPLT,LMAPCH,LCNTAM,
     -         LDEBUG,LIDENT,LKEYPL,LRNDMI,LPROPR,LPROF,LGSTOP,LGSIG,
     -         LSYNCH,LINPRD
       INTEGER LUNOUT,JFAIL,JEXMEM
       COMMON /PRTPLT/ LINPUT,LCELPR,LCELPL,LWRMRK,LISOCL,LCHGCH,
     -         LDRPLT,LDRPRT,LCLPRT,LCLPLT,LMAPCH,LCNTAM,
     -         LDEBUG,LIDENT,LKEYPL,LRNDMI,LPROPR,LPROF,LGSTOP,LGSIG,
     -         LSYNCH,LINPRD,LUNOUT,JFAIL,JEXMEM
       DOUBLE PRECISION FREQEL(mxngas),FREQSP(mxngas),FREINE(mxngas),
     -      FREATT(mxngas),FREION(mxngas),SPECS(32),SMSPEC,ENER,EPLT,
     -      SPECN,ERRFRE,FREQ,FREIN,FREEL,FRELV
       INTEGER NINEL,NELA,NREAL,I,J,K,J1,J2
*** Print header.
      IF(LBMCPR)WRITE(LUNOUT,15)
      IF(LBMCPR)WRITE(LUNOUT,15)
   15 FORMAT('----------------------------------------------------------
     /-------------------')
      IF(LBMCPR)WRITE(LUNOUT,110) SPEC(2048)
 110  FORMAT(2(/),' NUMBER OF COLLISIONS IN FINAL ENERGY BIN =',F8.1)
      NREAL=INT(XID)
*** Summing rearranged for adjustable number of gases.
       NINEL=0
       NELA=0
       DO 10 I=1,NGAS
       NINEL=NINEL+ICOLL(5*I-3)+ICOLL(5*I-2)+ICOLL(5*I-1)+ICOLL(5*I)
       NELA=NELA+ICOLL(5*I-4)
10     CONTINUE
      IF(TTOTS.EQ.0.0D0) THEN
       NREAL=NMAX
       TTOTS=ST
      ELSE
       NREAL=INT(XID)
      ENDIF
      FREQ=NREAL/TTOTS
      FREIN=NINEL/TTOTS
      FREEL=NELA/TTOTS
      IF(LBMCPR)WRITE(LUNOUT,220) FREQ,FREIN,FREEL
  220 FORMAT(/,6X,'TOTAL COLL. FREQ. =',D11.4,' (*10**12)/SEC.',/,2X,'IN
     /ELASTIC COLL. FREQ. =',D11.4,' (*10**12)/SEC.',/,4X,'ELASTIC COLL.
     / FREQ. =',D11.4,' (*10**12)/SEC.',/)
      IF(LBMCPR)WRITE(LUNOUT,15)
C     ILAST=INT(TMAX1)+1
C     IF(ILAST.GT.120) ILAST=120
C     IF(LBMCPR)WRITE(LUNOUT,1010) (TIME(I),I=1,ILAST)
C1010 FORMAT(/,6X,'DISTRIBUTION OF COLLISION TIMES IN 1 PECOSECOND BINS'
C    /,2(/),20(1X,6(F10.1,2X)/))
C     IF(LBMCPR)WRITE(LUNOUT,15)
      DO 1020 I=1,NGAS
      FREQEL(I)=ICOLL((5*I)-4)/TTOTS
      FREQSP(I)=ICOLL(5*I)/TTOTS
      FREINE(I)=ICOLL((5*I)-1)/TTOTS
      FREATT(I)=ICOLL((5*I)-2)/TTOTS
      FREION(I)=ICOLL((5*I)-3)/TTOTS
 1020 CONTINUE
C     IF(LBMCPR)WRITE(LUNOUT,1050)
C    -      (NAMEG(I),FREQEL(I),FREQSP(I),FREINE(I),FREATT(I),FREION(I),
C    -      I=1,NGAS)
C1050 FORMAT(/,5X,'COLLISION FREQUENCIES SORTED ACCORDING TO GAS AND TYP
C    /E OF COLLISION',/,5X,' IN UNITS OF 10**12/SEC.',2(/),'  GASES USED
C    /     ELASTIC     SUPERELAS   INELASTIC  ATTACHMENT  IONISATION ',2
C    /(/),6(A15,1X,5(D10.3,2X),/))
C     IF(LBMCPR)WRITE(LUNOUT,15)
      IF(LBMCPR)WRITE(LUNOUT,1060)
 1060 FORMAT(/,2X,'DETAILED COLLISION FREQUENCIES FOR EACH GAS IN UNITS
     /OF 10**12/SEC. :',2(/))
      DO 1100 J=1,NGAS
      IF(LBMCPR)WRITE(LUNOUT,1065) NAMEG(J)
 1065 FORMAT(3X,A15,/,'------------------',2(/))
*   Changed LAST to IPLAST (RV, 20/4/2005)
      DO 1090 K=1,IPLAST
      IF(IARRY(K).LE.(5*J).AND.IARRY(K).GT.(5*(J-1))) THEN
       FRELV=FREQ*ICOLN(K)/NREAL
       IF(ICOLN(K).EQ.0) THEN
        ERRFRE=0.0
       ELSE
        ERRFRE=100.0D0*SQRT(DBLE(ICOLN(K)))/DBLE(ICOLN(K))
       ENDIF
       IF(LBMCPR)WRITE(LUNOUT,1070) DSCRPT(K),FRELV,ERRFRE
 1070 FORMAT(3X,A30,3X,D11.4,' +-',F8.4,' %')
      ENDIF
 1090 CONTINUE
 1100 CONTINUE
      IF(LBMCPR)WRITE(LUNOUT,15)
      IF(LBMCPR)WRITE(LUNOUT,301)
  301 FORMAT(2(/),10X,' NORMALISED ENERGY DISTRIBUTION')
      J1=0
      J2=0
      SPECN=DBLE(NREAL)
      SMSPEC=0.0D0
      DO 350 K=1,2048
      SPEC(K)=SPEC(K)/SPECN
      J1=J1+1
      SMSPEC=SMSPEC+SPEC(K)
      IF(J1.LT.64) GO TO 350
      J2=J2+1
      SPECS(J2)=SMSPEC
      SMSPEC=0.0D0
      J1=0
  350 CONTINUE
      EPLT=EFINAL/32.0D0
      DO 420 I=1,32
      ENER=EPLT*(DBLE(I)-0.5D0)
      IF(LBMCPR)WRITE(LUNOUT,302) ENER,SPECS(I)
  302 FORMAT(6X,'E=',F12.3,6X,'SPEC=',D12.5)
  420 CONTINUE
      END
