CDECK  ID>, PRNTER.
      SUBROUTINE PRNTER
*-----------------------------------------------------------------------
*   PRNTER - Output routine
*   (Last changed on 19/ 9/05.)
*-----------------------------------------------------------------------
      IMPLICIT REAL*8 (A-H,O-Z)
*   Array dimensions.
       integer mxngas
       parameter(mxngas=6)
*-----------------------------------------------------------------------
*   MAGPAR - Interface parameters for gas mixing with Magboltz.
*   (Last changed on  2/ 3/08.)
*-----------------------------------------------------------------------
       INTEGER MXGNAM
       PARAMETER(MXGNAM=60)
       DOUBLE PRECISION FRAMIX
       LOGICAL LF0PLT,LCSPLT,LGKEEP,LBMCPR
       COMMON /MAGPAR/ FRAMIX(MXGNAM),LF0PLT,LCSPLT,LGKEEP,LBMCPR
       INTEGER NGAS,NSTEP,IDBG
       DOUBLE PRECISION EFINAL,ESTEP,AKT,ARY,TEMPC,TORR
       PARAMETER(ARY=13.60569172)
       COMMON/INPT/NGAS,NSTEP,EFINAL,ESTEP,AKT,TEMPC,TORR,IDBG
*   Grouped AN1 ... AN6 in ANn
       DOUBLE PRECISION ANn,AN,FRAC
       COMMON /RATIO/ ANn(mxngas),AN,FRAC(mxngas)
       DOUBLE PRECISION TMAX,SMALL,API,ESTART,THETA,PHI,TCFMAX,RSTART,
     -      EMAG
       INTEGER NMAX
       COMMON/SETP/TMAX,SMALL,API,ESTART,THETA,PHI,TCFMAX(8),RSTART,
     -      EMAG,NMAX
       DOUBLE PRECISION CON
       INTEGER ITHRM
       COMMON /THRM/ CON,ITHRM
       DOUBLE PRECISION EOVB,WB,BTHETA,BMAG
       COMMON/BFLD/EOVB,WB,BTHETA,BMAG
*   Sometimes IPLAST is called LAST
       DOUBLE PRECISION CF,EIN,TCF,RGAS,WPL
       INTEGER IARRY,IPN,IPLAST,ISIZE
       COMMON/LARGE/CF(2048,512),EIN(512),TCF(2048),IARRY(512),
     -      RGAS(512),IPN(512),WPL(512),IPLAST,ISIZE
*   Changed name of common from /NAMES/ to /MBGNAM/ for Mac OS X
       CHARACTER*15 NAMEG
       COMMON /MBGNAM/ NAMEG(mxngas)
       LOGICAL         LINPUT,LCELPR,LCELPL,LWRMRK,LISOCL,LCHGCH,
     -         LDRPLT,LDRPRT,LCLPRT,LCLPLT,LMAPCH,LCNTAM,
     -         LDEBUG,LIDENT,LKEYPL,LRNDMI,LPROPR,LPROF,LGSTOP,LGSIG,
     -         LSYNCH,LINPRD
       INTEGER LUNOUT,JFAIL,JEXMEM
       COMMON /PRTPLT/ LINPUT,LCELPR,LCELPL,LWRMRK,LISOCL,LCHGCH,
     -         LDRPLT,LDRPRT,LCLPRT,LCLPLT,LMAPCH,LCNTAM,
     -         LDEBUG,LIDENT,LKEYPL,LRNDMI,LPROPR,LPROF,LGSTOP,LGSIG,
     -         LSYNCH,LINPRD,LUNOUT,JFAIL,JEXMEM
      if(.not.lbmcpr)return
      WRITE(LUNOUT,1)
    1 FORMAT(2(/),10X,'PROGRAM MAGBOLTZ 2 VERSION 7.1 ',/)
      WRITE(LUNOUT,10) NGAS
   10 FORMAT(10X,'MONTE CARLO SOLUTION FOR MIXTURE OF ',I2,' GASES.',/,
     /5X,'------------------------------------------------------')
      WRITE(LUNOUT,30) (NAMEG(J),FRAC(J), J=1,NGAS)
  30  FORMAT(/,5X,'  GASES  USED ',5X,' PERCENTAGE USED ',2(/),6(6X,A15,
     /5X,F9.4,/))
      WRITE(LUNOUT,50) TEMPC,TORR
   50 FORMAT(/,2X,'GAS TEMPERATURE =',F6.1,' DEGREES CENTIGRADE.',/,2X,'
     /GAS PRESSURE = ',F7.1,' TORR.')
      WRITE(LUNOUT,60) EFINAL,NSTEP
  60  FORMAT(1(/),2X,'INTEGRATION FROM 0.0 TO ',F8.2,' EV.  IN ',I4,' ST
     /EPS. ')
C     IF(ITHRM.EQ.0) WRITE(LUNOUT,64)
C     IF(ITHRM.NE.0) WRITE(LUNOUT,65)
C 64  FORMAT(2(/),' THERMAL MOTION OF GAS NOT INCLUDED')
C 65  FORMAT(2(/),' THERMAL MOTION OF GAS INCLUDED')
  74  WRITE(LUNOUT,90) EMAG,BMAG,BTHETA,WB
  90  FORMAT(1(/),'  ELECTRIC FIELD =',F12.4,' VOLTS/CM.',/'  MAGNETIC F
     /IELD =',F11.4,' KILOGAUSS.',/,'  ANGLE BETWEEN ELECTRIC AND MAGNET
     /IC FIELD =',F10.3,' DEGREES.',/,'  CYCLOTRON FREQ. =',D12.3,' RADI
     /ANS/PICOSECOND')
      WRITE(LUNOUT,95) ESTART
  95  FORMAT(1(/),'  INITIAL ELECTRON ENERGY =',F8.3,' EV.')
C     WRITE(LUNOUT,96) RSTART
C 96  FORMAT(/,'  RANDOM NUMBER STARTER (SEED)=',F7.4)
      WRITE(LUNOUT,100) NMAX
 100  FORMAT(1(/),'  TOTAL NUMBER OF REAL COLLISIONS =',I11)
      WRITE(LUNOUT,110)  (TCFMAX(L),L=1,8)
  110 FORMAT(1(/),'  NULL COLLISION FREQUENCY AT  8 EQUALLY SPACED ENERG
     /Y INTERVALS (*10**12/SEC)',/,2(4(5X,D10.3)/))
      WRITE(LUNOUT,111)  (TCF(L),L=128,1920,256)
  111 FORMAT('  REAL COLLISION FREQUENCY AT  8 EQUALLY SPACED ENERGY INT
     /ERVALS (*10**12/SEC)',/,2(4(5X,D10.3)/))
      END
