CDECK  ID>, SHELLFI.
	subroutine shellfi
c
c	read shellfi.dat

	implicit none

c         include 'GoEvent.inc'
c      Main control variables


	integer soo		   ! Flag, allowing to print
				   !  to stream 'oo'
				   ! If it is 0, no print will be at all,
				   ! except the case of serious problems.
	integer oo		   ! The output stream logical number.
	integer qevt		   ! Quantity of events to produce.
	integer nevt		   ! Current number of the event.
	integer ninfo		   ! Quantity of the first events
				   ! to print debug info.
	integer ssimioni	   ! Flag to simulate ionization loss,
				   ! 0 - no ionization,
				   ! 1 - to simulate ionization.
				   !
				   !
				   !
	integer srandoff	   ! Flag to swich off the randomization
				   ! in function treatdel.
				   ! It is for debug and without guarantee.
	parameter (srandoff=0)	   ! Normal regim with randommization.

	integer pqup		   ! dimensions of arrays of auxiliary
				   ! parameters in abs.inc, rga.inc,
				   ! del.inc
	parameter (pqup=1)


	integer sret_err	! Sign to return the control from current
		! subroutine to which is called it if error is occured.
		! 1 - to return, 0 - to stop.
		! It is intended for handling with subroutine SHEED.
		! In the case of error it can return the control instead of
		! stop. But not for every possible errors return is done.
		! Some of the most original errors could lead to stop.
		! When working with HEED program, sret_err must be zero.
	integer s_err	! Sign of error.
		! 1 - error, 0 - no error

	character*9  TaskName	   ! Name of task, using for generating
				   ! file names.
	character*40 OutputFile	   ! Name of file with output listing.
				   ! Using only in IniHeed.
*** Common split in character and non-character parts (RV 26/10/2007).
	common / cGoEve /
     +	soo, oo,
     +	qevt,nevt,ninfo,
     +	ssimioni,
     +	sret_err, s_err
        common / cGoEveCHR /
     +	TaskName,
     +	OutputFile

	save / cGoEve /
	save / cGoEveCHR /
*** End of change

c 	include 'shellfi.inc'
	integer pqash		! Max. q. of shells
	parameter (pqash=7)
	integer zato		! Z of atom
	integer qash		! quantity of shells
	real athreshold,aweight	! threshold and weight of shells
	integer pqaener,qaener	! Max. and just q. of shell energy
	parameter (pqaener=500)
	real aener		! Energy
	real aphot		! Photoabsorbtion crossection
			! for this point of energy
	common / cshellfi /
     +		zato,
     +		qash,
     +		athreshold(pqash),aweight(pqash),
     +		qaener(pqash),
     +		aener(pqaener,pqash),aphot(pqaener,pqash)
	save / cshellfi /

c	integer i,z,n,k,j
        integer k1,l
c	character*1 a
c	integer ios

	qash=0		!sign of absence


c	The next code is generated by a computer program
c	on the basis of data file 'shellfi.dat'.


	if(zato.eq.3)then
	qash=2
	athreshold(1)=5.44515e-05
	aweight(1)=0.666667
	qaener(1)=36
	aener(1,1)=45.9
	aphot(1,1)=0
	aener(2,1)=50.4
	aphot(2,1)=809
	aener(3,1)=55.4
	aphot(3,1)=6080
	aener(4,1)=60.9
	aphot(4,1)=8810
	aener(5,1)=66.9
	aphot(5,1)=8700
	aener(6,1)=73.5
	aphot(6,1)=7210
	aener(7,1)=80.8
	aphot(7,1)=5530
	aener(8,1)=88.8
	aphot(8,1)=4420
	aener(9,1)=97.6
	aphot(9,1)=3840
	aener(10,1)=107
	aphot(10,1)=3090
	aener(11,1)=118
	aphot(11,1)=2520
	aener(12,1)=129
	aphot(12,1)=2040
	aener(13,1)=142
	aphot(13,1)=1820
	aener(14,1)=156
	aphot(14,1)=1460
	aener(15,1)=172
	aphot(15,1)=1050
	aener(16,1)=189
	aphot(16,1)=866
	aener(17,1)=207
	aphot(17,1)=717
	aener(18,1)=228
	aphot(18,1)=594
	aener(19,1)=275
	aphot(19,1)=407
	aener(20,1)=303
	aphot(20,1)=337
	aener(21,1)=500
	aphot(21,1)=25.0178
	aener(22,1)=700
	aphot(22,1)=10.0856
	aener(23,1)=900
	aphot(23,1)=5.11698
	aener(24,1)=1100
	aphot(24,1)=2.97651
	aener(25,1)=1300
	aphot(25,1)=1.89593
	aener(26,1)=1600
	aphot(26,1)=1.08229
	aener(27,1)=2000
	aphot(27,1)=0.592498
	aener(28,1)=4000
	aphot(28,1)=0.0888748
	aener(29,1)=6000
	aphot(29,1)=0.0296249
	aener(30,1)=8000
	aphot(30,1)=0.0148125
	aener(31,1)=10000
	aphot(31,1)=0.00888748
	aener(32,1)=20000
	aphot(32,1)=0.00503624
	aener(33,1)=30000
	aphot(33,1)=0.00444374
	aener(34,1)=40000
	aphot(34,1)=0.00414749
	aener(35,1)=50000
	aphot(35,1)=0.00399937
	aener(36,1)=80000
	aphot(36,1)=0.00355499
	athreshold(2)=1e-05
	aweight(2)=0.333333
	qaener(2)=29
	aener(1,2)=8.4
	aphot(1,2)=0
	aener(2,2)=9.23
	aphot(2,2)=2100
	aener(3,2)=10.1
	aphot(3,2)=16900
	aener(4,2)=11.1
	aphot(4,2)=25500
	aener(5,2)=12.2
	aphot(5,2)=22900
	aener(6,2)=13.5
	aphot(6,2)=17600
	aener(7,2)=14.8
	aphot(7,2)=15000
	aener(8,2)=16.2
	aphot(8,2)=10700
	aener(9,2)=17.9
	aphot(9,2)=8880
	aener(10,2)=19.6
	aphot(10,2)=7360
	aener(11,2)=21.6
	aphot(11,2)=6090
	aener(12,2)=23.7
	aphot(12,2)=5040
	aener(13,2)=26
	aphot(13,2)=4180
	aener(14,2)=28.6
	aphot(14,2)=3460
	aener(15,2)=31.5
	aphot(15,2)=2860
	aener(16,2)=34.6
	aphot(16,2)=2370
	aener(17,2)=38
	aphot(17,2)=1960
	aener(18,2)=41.7
	aphot(18,2)=1630
	aener(19,2)=45.9
	aphot(19,2)=1350
	aener(20,2)=50.4
	aphot(20,2)=1110
	aener(21,2)=55.4
	aphot(21,2)=923
	aener(22,2)=60.9
	aphot(22,2)=764
	aener(23,2)=66.9
	aphot(23,2)=633
	aener(24,2)=73.5
	aphot(24,2)=524
	aener(25,2)=80.8
	aphot(25,2)=434
	aener(26,2)=88.8
	aphot(26,2)=359
	aener(27,2)=97.6
	aphot(27,2)=0.298
	aener(28,2)=107
	aphot(28,2)=0.00246
	aener(29,2)=118
	aphot(29,2)=0.000204
	endif
	if(zato.eq.6)then
	qash=2
	athreshold(1)=0.000309
	aweight(1)=0.423871
	qaener(1)=24
	aener(1,1)=228
	aphot(1,1)=16900
	aener(2,1)=251
	aphot(2,1)=23300
	aener(3,1)=275
	aphot(3,1)=30700
	aener(4,1)=303
	aphot(4,1)=38600
	aener(5,1)=333
	aphot(5,1)=37200
	aener(6,1)=365
	aphot(6,1)=31200
	aener(7,1)=402
	aphot(7,1)=24900
	aener(8,1)=441
	aphot(8,1)=20900
	aener(9,1)=485
	aphot(9,1)=18000
	aener(10,1)=533
	aphot(10,1)=14800
	aener(11,1)=586
	aphot(11,1)=11400
	aener(12,1)=644
	aphot(12,1)=8620
	aener(13,1)=707
	aphot(13,1)=7090
	aener(14,1)=777
	aphot(14,1)=5440
	aener(15,1)=854
	aphot(15,1)=3960
	aener(16,1)=939
	aphot(16,1)=3080
	aener(17,1)=1030
	aphot(17,1)=2400
	aener(18,1)=3500
	aphot(18,1)=60
	aener(19,1)=4000
	aphot(19,1)=33
	aener(20,1)=10000
	aphot(20,1)=2
	aener(21,1)=20000
	aphot(21,1)=0.4
	aener(22,1)=30000
	aphot(22,1)=0.27
	aener(23,1)=50000
	aphot(23,1)=0.2
	aener(24,1)=100000
	aphot(24,1)=0.17
	athreshold(2)=1.03321e-05
	aweight(2)=0.576129
	qaener(2)=14
	aener(1,2)=6.19927
	aphot(1,2)=0
	aener(2,2)=8.26569
	aphot(2,2)=0
	aener(3,2)=10.3321
	aphot(3,2)=12.6
	aener(4,2)=12.3985
	aphot(4,2)=11.2
	aener(5,2)=15.4982
	aphot(5,2)=9.1
	aener(6,2)=20.6642
	aphot(6,2)=7.3
	aener(7,2)=30.9964
	aphot(7,2)=4.4
	aener(8,2)=41.3285
	aphot(8,2)=2.9
	aener(9,2)=61.9927
	aphot(9,2)=1.45
	aener(10,2)=82.6569
	aphot(10,2)=0.88
	aener(11,2)=103.321
	aphot(11,2)=0.59
	aener(12,2)=123.985
	aphot(12,2)=0.4
	aener(13,2)=154.982
	aphot(13,2)=0.24
	aener(14,2)=206.642
	aphot(14,2)=0.108
	endif
	if(zato.eq.7)then
	qash=2
	athreshold(1)=0.000413
	aweight(1)=0.318257
	qaener(1)=8
	aener(1,1)=309.964
	aphot(1,1)=0.07
	aener(2,1)=413.285
	aphot(2,1)=0.68
	aener(3,1)=619.927
	aphot(3,1)=0.255
	aener(4,1)=826.569
	aphot(4,1)=0.125
	aener(5,1)=1033.21
	aphot(5,1)=0.075
	aener(6,1)=1239.85
	aphot(6,1)=0.047
	aener(7,1)=1549.82
	aphot(7,1)=0.026
	aener(8,1)=2066.42
	aphot(8,1)=0.012
	athreshold(2)=1.23985e-05
	aweight(2)=0.681743
	qaener(2)=15
	aener(1,2)=6.19927
	aphot(1,2)=0
	aener(2,2)=8.26569
	aphot(2,2)=0
	aener(3,2)=10.3321
	aphot(3,2)=0
	aener(4,2)=12.3985
	aphot(4,2)=11.95
	aener(5,2)=15.4982
	aphot(5,2)=11.9
	aener(6,2)=20.6642
	aphot(6,2)=9.65
	aener(7,2)=30.9964
	aphot(7,2)=7.8
	aener(8,2)=41.3285
	aphot(8,2)=5.4
	aener(9,2)=61.9927
	aphot(9,2)=2.9
	aener(10,2)=82.6569
	aphot(10,2)=1.75
	aener(11,2)=103.321
	aphot(11,2)=1.1
	aener(12,2)=123.985
	aphot(12,2)=0.65
	aener(13,2)=154.982
	aphot(13,2)=0.39
	aener(14,2)=206.642
	aphot(14,2)=0.208
	aener(15,2)=309.964
	aphot(15,2)=0.07
	endif
	if(zato.eq.8)then
	qash=2
	athreshold(1)=0.00062
	aweight(1)=0.240404
	qaener(1)=20
	aener(1,1)=586
	aphot(1,1)=13300
	aener(2,1)=644
	aphot(2,1)=14200
	aener(3,1)=707
	aphot(3,1)=11800
	aener(4,1)=777
	aphot(4,1)=9270
	aener(5,1)=854
	aphot(5,1)=7100
	aener(6,1)=939
	aphot(6,1)=5880
	aener(7,1)=1030
	aphot(7,1)=4660
	aener(8,1)=1130
	aphot(8,1)=3690
	aener(9,1)=1250
	aphot(9,1)=2790
	aener(10,1)=1370
	aphot(10,1)=2260
	aener(11,1)=1500
	aphot(11,1)=1740
	aener(12,1)=1650
	aphot(12,1)=1340
	aener(13,1)=1820
	aphot(13,1)=1060
	aener(14,1)=3500
	aphot(14,1)=187.5
	aener(15,1)=4000
	aphot(15,1)=118.125
	aener(16,1)=10000
	aphot(16,1)=6.75
	aener(17,1)=20000
	aphot(17,1)=0.9
	aener(18,1)=30000
	aphot(18,1)=0.39375
	aener(19,1)=50000
	aphot(19,1)=0.255
	aener(20,1)=100000
	aphot(20,1)=0.19875
	athreshold(2)=2.06642e-05
	aweight(2)=0.759596
	qaener(2)=16
	aener(1,2)=6.19927
	aphot(1,2)=0
	aener(2,2)=8.26569
	aphot(2,2)=0
	aener(3,2)=10.3321
	aphot(3,2)=0
	aener(4,2)=12.3985
	aphot(4,2)=0
	aener(5,2)=15.4982
	aphot(5,2)=9
	aener(6,2)=20.6642
	aphot(6,2)=9.65
	aener(7,2)=30.9964
	aphot(7,2)=8.75
	aener(8,2)=41.3285
	aphot(8,2)=7.42
	aener(9,2)=61.9927
	aphot(9,2)=4.65
	aener(10,2)=82.6569
	aphot(10,2)=2.7
	aener(11,2)=103.321
	aphot(11,2)=1.77
	aener(12,2)=123.985
	aphot(12,2)=1.12
	aener(13,2)=154.982
	aphot(13,2)=0.7
	aener(14,2)=206.642
	aphot(14,2)=0.385
	aener(15,2)=309.964
	aphot(15,2)=0.16
	aener(16,2)=413.285
	aphot(16,2)=0.065
	endif
	if(zato.eq.9)then
	qash=2
	athreshold(1)=0.000827
	aweight(1)=0.185727
	qaener(1)=6
	aener(1,1)=619.927
	aphot(1,1)=0.05
	aener(2,1)=826.569
	aphot(2,1)=0.305
	aener(3,1)=1033.21
	aphot(3,1)=0.17
	aener(4,1)=1239.85
	aphot(4,1)=0.115
	aener(5,1)=1549.82
	aphot(5,1)=0.067
	aener(6,1)=2066.42
	aphot(6,1)=0.03
	athreshold(2)=3.09964e-05
	aweight(2)=0.814273
	qaener(2)=17
	aener(1,2)=6.19927
	aphot(1,2)=0
	aener(2,2)=8.26569
	aphot(2,2)=0
	aener(3,2)=10.3321
	aphot(3,2)=0
	aener(4,2)=12.3985
	aphot(4,2)=0
	aener(5,2)=15.4982
	aphot(5,2)=0
	aener(6,2)=20.6642
	aphot(6,2)=0
	aener(7,2)=30.9964
	aphot(7,2)=10.6
	aener(8,2)=41.3285
	aphot(8,2)=10.1
	aener(9,2)=61.9927
	aphot(9,2)=6.7
	aener(10,2)=82.6569
	aphot(10,2)=4.1
	aener(11,2)=103.321
	aphot(11,2)=2.6
	aener(12,2)=123.985
	aphot(12,2)=1.8
	aener(13,2)=154.982
	aphot(13,2)=1.3
	aener(14,2)=206.642
	aphot(14,2)=0.59
	aener(15,2)=309.964
	aphot(15,2)=0.245
	aener(16,2)=413.285
	aphot(16,2)=0.124
	aener(17,2)=619.927
	aphot(17,2)=0.05
	endif
	if(zato.eq.10)then
	qash=2
	athreshold(1)=0.001033
	aweight(1)=0.117826
	qaener(1)=5
	aener(1,1)=826.569
	aphot(1,1)=0.03
	aener(2,1)=1033.21
	aphot(2,1)=0.205
	aener(3,1)=1239.85
	aphot(3,1)=0.135
	aener(4,1)=1549.82
	aphot(4,1)=0.077
	aener(5,1)=2066.42
	aphot(5,1)=0.039
	athreshold(2)=3.09964e-05
	aweight(2)=0.882174
	qaener(2)=18
	aener(1,2)=6.19927
	aphot(1,2)=0
	aener(2,2)=8.26569
	aphot(2,2)=0
	aener(3,2)=10.3321
	aphot(3,2)=0
	aener(4,2)=12.3985
	aphot(4,2)=0
	aener(5,2)=15.4982
	aphot(5,2)=0
	aener(6,2)=20.6642
	aphot(6,2)=5.85
	aener(7,2)=30.9964
	aphot(7,2)=8.8
	aener(8,2)=41.3285
	aphot(8,2)=8.7
	aener(9,2)=61.9927
	aphot(9,2)=7.3
	aener(10,2)=82.6569
	aphot(10,2)=5.6
	aener(11,2)=103.321
	aphot(11,2)=4
	aener(12,2)=123.985
	aphot(12,2)=2.8
	aener(13,2)=154.982
	aphot(13,2)=1.75
	aener(14,2)=206.642
	aphot(14,2)=0.91
	aener(15,2)=309.964
	aphot(15,2)=0.36
	aener(16,2)=413.285
	aphot(16,2)=0.17
	aener(17,2)=619.927
	aphot(17,2)=0.063
	aener(18,2)=826.569
	aphot(18,2)=0.03
	endif
	if(zato.eq.17)then
	qash=4
	athreshold(1)=0.003485
	aweight(1)=0.117088
	qaener(1)=69
	aener(1,1)=3365.37
	aphot(1,1)=0
	aener(2,1)=3536.21
	aphot(2,1)=0.050227
	aener(3,1)=3715.72
	aphot(3,1)=0.0574
	aener(4,1)=3904.35
	aphot(4,1)=0.051988
	aener(5,1)=4102.55
	aphot(5,1)=0.047086
	aener(6,1)=4310.81
	aphot(6,1)=0.042647
	aener(7,1)=4529.65
	aphot(7,1)=0.038625
	aener(8,1)=4759.59
	aphot(8,1)=0.034983
	aener(9,1)=5001.2
	aphot(9,1)=0.031685
	aener(10,1)=5255.08
	aphot(10,1)=0.028697
	aener(11,1)=5521.85
	aphot(11,1)=0.025992
	aener(12,1)=5802.16
	aphot(12,1)=0.023541
	aener(13,1)=6096.71
	aphot(13,1)=0.021321
	aener(14,1)=6406.2
	aphot(14,1)=0.019311
	aener(15,1)=6731.4
	aphot(15,1)=0.01749
	aener(16,1)=7073.12
	aphot(16,1)=0.015841
	aener(17,1)=7432.17
	aphot(17,1)=0.014347
	aener(18,1)=7809.46
	aphot(18,1)=0.012995
	aener(19,1)=8205.9
	aphot(19,1)=0.011769
	aener(20,1)=8622.46
	aphot(20,1)=0.01066
	aener(21,1)=9060.17
	aphot(21,1)=0.009654
	aener(22,1)=9520.11
	aphot(22,1)=0.008744
	aener(23,1)=10003.4
	aphot(23,1)=0.00792
	aener(24,1)=10511.2
	aphot(24,1)=0.007173
	aener(25,1)=11044.8
	aphot(25,1)=0.006497
	aener(26,1)=11605.5
	aphot(26,1)=0.005884
	aener(27,1)=12194.6
	aphot(27,1)=0.005329
	aener(28,1)=12813.6
	aphot(28,1)=0.004827
	aener(29,1)=13464.1
	aphot(29,1)=0.004372
	aener(30,1)=14147.6
	aphot(30,1)=0.003959
	aener(31,1)=14865.8
	aphot(31,1)=0.003586
	aener(32,1)=15620.4
	aphot(32,1)=0.003248
	aener(33,1)=16413.4
	aphot(33,1)=0.002942
	aener(34,1)=17246.6
	aphot(34,1)=0.002664
	aener(35,1)=18122.1
	aphot(35,1)=0.002413
	aener(36,1)=19042.1
	aphot(36,1)=0.002186
	aener(37,1)=20008.7
	aphot(37,1)=0.00198
	aener(38,1)=21024.4
	aphot(38,1)=0.001793
	aener(39,1)=22091.7
	aphot(39,1)=0.001624
	aener(40,1)=23213.2
	aphot(40,1)=0.001471
	aener(41,1)=24391.6
	aphot(41,1)=0.001332
	aener(42,1)=25629.8
	aphot(42,1)=0.001206
	aener(43,1)=26930.9
	aphot(43,1)=0.001093
	aener(44,1)=28298
	aphot(44,1)=0.00099
	aener(45,1)=29734.5
	aphot(45,1)=0.000896
	aener(46,1)=31243.9
	aphot(46,1)=0.000812
	aener(47,1)=32830
	aphot(47,1)=0.000735
	aener(48,1)=34496.6
	aphot(48,1)=0.000666
	aener(49,1)=36247.8
	aphot(49,1)=0.000603
	aener(50,1)=38087.9
	aphot(50,1)=0.000546
	aener(51,1)=40021.3
	aphot(51,1)=0.000495
	aener(52,1)=42053
	aphot(52,1)=0.000448
	aener(53,1)=44187.8
	aphot(53,1)=0.000406
	aener(54,1)=46430.9
	aphot(54,1)=0.000368
	aener(55,1)=48787.9
	aphot(55,1)=0.000333
	aener(56,1)=51264.6
	aphot(56,1)=0.000302
	aener(57,1)=53867
	aphot(57,1)=0.000273
	aener(58,1)=56601.5
	aphot(58,1)=0.000247
	aener(59,1)=59474.8
	aphot(59,1)=0.000224
	aener(60,1)=62494
	aphot(60,1)=0.000203
	aener(61,1)=65666.4
	aphot(61,1)=0.000184
	aener(62,1)=68999.9
	aphot(62,1)=0.000166
	aener(63,1)=72502.6
	aphot(63,1)=0.000151
	aener(64,1)=76183.1
	aphot(64,1)=0.000137
	aener(65,1)=80050.5
	aphot(65,1)=0.000124
	aener(66,1)=84114.2
	aphot(66,1)=0.000112
	aener(67,1)=88384.1
	aphot(67,1)=0.000101
	aener(68,1)=92870.9
	aphot(68,1)=9.18846e-05
	aener(69,1)=97585.4
	aphot(69,1)=8.32209e-05
	athreshold(2)=0.000207
	aweight(2)=0.635323
	qaener(2)=10
	aener(1,2)=154.982
	aphot(1,2)=0.6
	aener(2,2)=206.642
	aphot(2,2)=6.4
	aener(3,2)=309.964
	aphot(3,2)=2.45
	aener(4,2)=413.285
	aphot(4,2)=1.4
	aener(5,2)=619.927
	aphot(5,2)=0.45
	aener(6,2)=826.569
	aphot(6,2)=0.22
	aener(7,2)=1033.21
	aphot(7,2)=0.123
	aener(8,2)=1239.85
	aphot(8,2)=0.079
	aener(9,2)=1549.82
	aphot(9,2)=0.047
	aener(10,2)=2066.42
	aphot(10,2)=0.0195
	athreshold(3)=6.19927e-05
	aweight(3)=0.061546
	qaener(3)=6
	aener(1,3)=41.3285
	aphot(1,3)=1.07
	aener(2,3)=61.9927
	aphot(2,3)=1.35
	aener(3,3)=82.6569
	aphot(3,3)=1.22
	aener(4,3)=103.321
	aphot(4,3)=1
	aener(5,3)=123.985
	aphot(5,3)=0.82
	aener(6,3)=154.982
	aphot(6,3)=0.6
	athreshold(4)=1.54982e-05
	aweight(4)=0.186043
	qaener(4)=8
	aener(1,4)=6.19927
	aphot(1,4)=0
	aener(2,4)=8.26569
	aphot(2,4)=0
	aener(3,4)=10.3321
	aphot(3,4)=0
	aener(4,4)=12.3985
	aphot(4,4)=0
	aener(5,4)=15.4982
	aphot(5,4)=59
	aener(6,4)=20.6642
	aphot(6,4)=11
	aener(7,4)=30.9964
	aphot(7,4)=1.35
	aener(8,4)=41.3285
	aphot(8,4)=1.07
	endif
	if(zato.eq.18)then
	qash=4
	athreshold(1)=0.003934
	aweight(1)=0.114211
	qaener(1)=67
	aener(1,1)=3715.72
	aphot(1,1)=0
	aener(2,1)=3904.35
	aphot(2,1)=0.020435
	aener(3,1)=4102.55
	aphot(3,1)=0.053399
	aener(4,1)=4310.81
	aphot(4,1)=0.048364
	aener(5,1)=4529.65
	aphot(5,1)=0.043804
	aener(6,1)=4759.59
	aphot(6,1)=0.039674
	aener(7,1)=5001.2
	aphot(7,1)=0.035933
	aener(8,1)=5255.08
	aphot(8,1)=0.032545
	aener(9,1)=5521.85
	aphot(9,1)=0.029476
	aener(10,1)=5802.16
	aphot(10,1)=0.026697
	aener(11,1)=6096.71
	aphot(11,1)=0.02418
	aener(12,1)=6406.2
	aphot(12,1)=0.0219
	aener(13,1)=6731.4
	aphot(13,1)=0.019835
	aener(14,1)=7073.12
	aphot(14,1)=0.017965
	aener(15,1)=7432.17
	aphot(15,1)=0.016271
	aener(16,1)=7809.46
	aphot(16,1)=0.014737
	aener(17,1)=8205.9
	aphot(17,1)=0.013347
	aener(18,1)=8622.46
	aphot(18,1)=0.012089
	aener(19,1)=9060.17
	aphot(19,1)=0.010949
	aener(20,1)=9520.11
	aphot(20,1)=0.009917
	aener(21,1)=10003.4
	aphot(21,1)=0.008982
	aener(22,1)=10511.2
	aphot(22,1)=0.008135
	aener(23,1)=11044.8
	aphot(23,1)=0.007368
	aener(24,1)=11605.5
	aphot(24,1)=0.006673
	aener(25,1)=12194.6
	aphot(25,1)=0.006044
	aener(26,1)=12813.6
	aphot(26,1)=0.005474
	aener(27,1)=13464.1
	aphot(27,1)=0.004958
	aener(28,1)=14147.6
	aphot(28,1)=0.00449
	aener(29,1)=14865.8
	aphot(29,1)=0.004067
	aener(30,1)=15620.4
	aphot(30,1)=0.003683
	aener(31,1)=16413.4
	aphot(31,1)=0.003336
	aener(32,1)=17246.6
	aphot(32,1)=0.003022
	aener(33,1)=18122.1
	aphot(33,1)=0.002737
	aener(34,1)=19042.1
	aphot(34,1)=0.002479
	aener(35,1)=20008.7
	aphot(35,1)=0.002245
	aener(36,1)=21024.4
	aphot(36,1)=0.002033
	aener(37,1)=22091.7
	aphot(37,1)=0.001842
	aener(38,1)=23213.2
	aphot(38,1)=0.001668
	aener(39,1)=24391.6
	aphot(39,1)=0.001511
	aener(40,1)=25629.8
	aphot(40,1)=0.001368
	aener(41,1)=26930.9
	aphot(41,1)=0.001239
	aener(42,1)=28298
	aphot(42,1)=0.001122
	aener(43,1)=29734.5
	aphot(43,1)=0.001017
	aener(44,1)=31243.9
	aphot(44,1)=0.000921
	aener(45,1)=32830
	aphot(45,1)=0.000834
	aener(46,1)=34496.6
	aphot(46,1)=0.000755
	aener(47,1)=36247.8
	aphot(47,1)=0.000684
	aener(48,1)=38087.9
	aphot(48,1)=0.00062
	aener(49,1)=40021.3
	aphot(49,1)=0.000561
	aener(50,1)=42053
	aphot(50,1)=0.000508
	aener(51,1)=44187.8
	aphot(51,1)=0.00046
	aener(52,1)=46430.9
	aphot(52,1)=0.000417
	aener(53,1)=48787.9
	aphot(53,1)=0.000378
	aener(54,1)=51264.6
	aphot(54,1)=0.000342
	aener(55,1)=53867
	aphot(55,1)=0.00031
	aener(56,1)=56601.5
	aphot(56,1)=0.000281
	aener(57,1)=59474.8
	aphot(57,1)=0.000254
	aener(58,1)=62494
	aphot(58,1)=0.00023
	aener(59,1)=65666.4
	aphot(59,1)=0.000208
	aener(60,1)=68999.9
	aphot(60,1)=0.000189
	aener(61,1)=72502.6
	aphot(61,1)=0.000171
	aener(62,1)=76183.1
	aphot(62,1)=0.000155
	aener(63,1)=80050.5
	aphot(63,1)=0.00014
	aener(64,1)=84114.2
	aphot(64,1)=0.000127
	aener(65,1)=88384.1
	aphot(65,1)=0.000115
	aener(66,1)=92870.9
	aphot(66,1)=0.000104
	aener(67,1)=97585.4
	aphot(67,1)=9.43788e-05
	athreshold(2)=0.00031
	aweight(2)=0.438551
	qaener(2)=10
	aener(1,2)=206.642
	aphot(1,2)=0.55
	aener(2,2)=309.964
	aphot(2,2)=2.52
	aener(3,2)=413.285
	aphot(3,2)=1.66
	aener(4,2)=619.927
	aphot(4,2)=0.62
	aener(5,2)=826.569
	aphot(5,2)=0.29
	aener(6,2)=1033.21
	aphot(6,2)=0.16
	aener(7,2)=1239.85
	aphot(7,2)=0.1
	aener(8,2)=1549.82
	aphot(8,2)=0.06
	aener(9,2)=2066.42
	aphot(9,2)=0.026
	aener(10,2)=3099.64
	aphot(10,2)=0.0085
	athreshold(3)=6.19927e-05
	aweight(3)=0.092874
	qaener(3)=7
	aener(1,3)=41.3285
	aphot(1,3)=1
	aener(2,3)=61.9927
	aphot(2,3)=1.52
	aener(3,3)=82.6569
	aphot(3,3)=1.52
	aener(4,3)=103.321
	aphot(4,3)=1.33
	aener(5,3)=123.985
	aphot(5,3)=1.1
	aener(6,3)=154.982
	aphot(6,3)=0.85
	aener(7,3)=206.642
	aphot(7,3)=0.55
	athreshold(4)=1.54982e-05
	aweight(4)=0.354364
	qaener(4)=8
	aener(1,4)=6.19927
	aphot(1,4)=0
	aener(2,4)=8.26569
	aphot(2,4)=0
	aener(3,4)=10.3321
	aphot(3,4)=0
	aener(4,4)=12.3985
	aphot(4,4)=0
	aener(5,4)=15.4982
	aphot(5,4)=60
	aener(6,4)=20.6642
	aphot(6,4)=52.5
	aener(7,4)=30.9964
	aphot(7,4)=2
	aener(8,4)=41.3285
	aphot(8,4)=1
	endif
	if(zato.eq.36)then
	qash=4
	athreshold(1)=0.015498
	aweight(1)=0.04453
	qaener(1)=4
	aener(1,1)=12398.5
	aphot(1,1)=0.0032
	aener(2,1)=15498.2
	aphot(2,1)=0.0205
	aener(3,1)=20664.2
	aphot(3,1)=0.0079
	aener(4,1)=30996.4
	aphot(4,1)=0.0022
	athreshold(2)=0.00155
	aweight(2)=0.262277
	qaener(2)=9
	aener(1,2)=1239.85
	aphot(1,2)=0.22
	aener(2,2)=1549.82
	aphot(2,2)=0.7
	aener(3,2)=2066.42
	aphot(3,2)=0.41
	aener(4,2)=3099.64
	aphot(4,2)=0.14
	aener(5,2)=4132.85
	aphot(5,2)=0.061
	aener(6,2)=6199.27
	aphot(6,2)=0.02
	aener(7,2)=8265.69
	aphot(7,2)=0.0096
	aener(8,2)=10332.1
	aphot(8,2)=0.0053
	aener(9,2)=12398.5
	aphot(9,2)=0.0032
	athreshold(3)=0.000207
	aweight(3)=0.594165
	qaener(3)=11
	aener(1,3)=82.6569
	aphot(1,3)=0.7
	aener(2,3)=103.321
	aphot(2,3)=1.2
	aener(3,3)=123.985
	aphot(3,3)=3.4
	aener(4,3)=154.982
	aphot(4,3)=6.1
	aener(5,3)=206.642
	aphot(5,3)=6.8
	aener(6,3)=309.964
	aphot(6,3)=4.4
	aener(7,3)=413.285
	aphot(7,3)=2.65
	aener(8,3)=619.927
	aphot(8,3)=0.95
	aener(9,3)=826.569
	aphot(9,3)=0.54
	aener(10,3)=1033.21
	aphot(10,3)=0.34
	aener(11,3)=1239.85
	aphot(11,3)=0.22
	athreshold(4)=1.54982e-05
	aweight(4)=0.099027
	qaener(4)=10
	aener(1,4)=6.19927
	aphot(1,4)=0
	aener(2,4)=8.26569
	aphot(2,4)=0
	aener(3,4)=10.3321
	aphot(3,4)=0
	aener(4,4)=12.3985
	aphot(4,4)=0
	aener(5,4)=15.4982
	aphot(5,4)=60
	aener(6,4)=20.6642
	aphot(6,4)=7.2
	aener(7,4)=30.9964
	aphot(7,4)=1.75
	aener(8,4)=41.3285
	aphot(8,4)=1.05
	aener(9,4)=61.9927
	aphot(9,4)=0.75
	aener(10,4)=82.6569
	aphot(10,4)=0.7
	endif
	if(zato.eq.54)then
	qash=6
	athreshold(1)=0.041328
	aweight(1)=0.017971
	qaener(1)=3
	aener(1,1)=30996.4
	aphot(1,1)=0.0013
	aener(2,1)=41328.5
	aphot(2,1)=0.0046
	aener(3,1)=61992.7
	aphot(3,1)=0.0015
	athreshold(2)=0.006199
	aweight(2)=0.114379
	qaener(2)=7
	aener(1,2)=4132.85
	aphot(1,2)=0.071
	aener(2,2)=6199.27
	aphot(2,2)=0.11
	aener(3,2)=8265.69
	aphot(3,2)=0.051
	aener(4,2)=12398.5
	aphot(4,2)=0.017
	aener(5,2)=15498.2
	aphot(5,2)=0.009
	aener(6,2)=20664.2
	aphot(6,2)=0.004
	aener(7,2)=30996.4
	aphot(7,2)=0.0013
	athreshold(3)=0.000827
	aweight(3)=0.411049
	qaener(3)=8
	aener(1,3)=619.927
	aphot(1,3)=0.63
	aener(2,3)=826.569
	aphot(2,3)=2.3
	aener(3,3)=1033.21
	aphot(3,3)=1.8
	aener(4,3)=1239.85
	aphot(4,3)=1.37
	aener(5,3)=1549.82
	aphot(5,3)=0.86
	aener(6,3)=2066.42
	aphot(6,3)=0.42
	aener(7,3)=3099.64
	aphot(7,3)=0.15
	aener(8,3)=4132.85
	aphot(8,3)=0.071
	athreshold(4)=0.00031
	aweight(4)=0.075061
	qaener(4)=4
	aener(1,4)=206.642
	aphot(1,4)=1
	aener(2,4)=309.964
	aphot(2,4)=1.15
	aener(3,4)=413.285
	aphot(3,4)=1
	aener(4,4)=619.927
	aphot(4,4)=0.63
	athreshold(5)=8.26569e-05
	aweight(5)=0.273675
	qaener(5)=6
	aener(1,5)=61.9927
	aphot(1,5)=0.67
	aener(2,5)=82.6569
	aphot(2,5)=48
	aener(3,5)=103.321
	aphot(3,5)=14
	aener(4,5)=123.985
	aphot(4,5)=2.5
	aener(5,5)=154.982
	aphot(5,5)=1.1
	aener(6,5)=206.642
	aphot(6,5)=1
	athreshold(6)=1.23985e-05
	aweight(6)=0.107866
	qaener(6)=9
	aener(1,6)=6.19927
	aphot(1,6)=0
	aener(2,6)=8.26569
	aphot(2,6)=0
	aener(3,6)=10.3321
	aphot(3,6)=0
	aener(4,6)=12.3985
	aphot(4,6)=110
	aener(5,6)=15.4982
	aphot(5,6)=37
	aener(6,6)=20.6642
	aphot(6,6)=10
	aener(7,6)=30.9964
	aphot(7,6)=2.2
	aener(8,6)=41.3285
	aphot(8,6)=1.1
	aener(9,6)=61.9927
	aphot(9,6)=0.67
	endif

c	end of computer code


	do k1=1,qash
	do l=1,qaener(k1)	


	aener(l,k1)=aener(l,k1)*1.e-6

	enddo
	enddo


        if(soo.eq.1)then
	if(qash.eq.0)then
	write(oo,*)' Worning of shellfi: atom z=',zato,' is not found.'
        write(oo,*)
     +  '  The data will be seached by shteor, accuracy will be lower.'

	endif
	endif

c	call prishellfi

	end


	subroutine shteor(num)

c	read shteor.dat

	implicit none

c 	include 'shellfi.inc'
	integer pqash		! Max. q. of shells
	parameter (pqash=7)
	integer zato		! Z of atom
	integer qash		! quantity of shells
	real athreshold,aweight	! threshold and weight of shells
	integer pqaener,qaener	! Max. and just q. of shell energy
	parameter (pqaener=500)
	real aener		! Energy
	real aphot		! Photoabsorbtion crossection
			! for this point of energy
	common / cshellfi /
     +		zato,
     +		qash,
     +		athreshold(pqash),aweight(pqash),
     +		qaener(pqash),
     +		aener(pqaener,pqash),aphot(pqaener,pqash)
	save / cshellfi /
c 	include 'LibAtMat.inc'
c	Numbers(pointers) of atoms in atom.inc.

c	Since for some of them a special treatment is provided
c	in subroutine Iniatom and this subroutine recognize them by number,
c	the user must not initialize another atoms on these places,
c	even if subroutine AtomsByDefault is not called.
c	Another atoms can be initialized on free places.

	integer num_H
	integer num_H3
	integer num_H4
	integer num_He
	integer num_Li
	integer num_C
	integer num_C1
	integer num_C2
	integer num_C3
c	integer num_C4
	integer num_N
	integer num_O
	integer num_F
	integer num_Ne
	integer num_Al
	integer num_Si
	integer num_Ar
	integer num_Kr
	integer num_Xe
	parameter (num_H  = 1  )
	parameter (num_H3 = 2  )
	parameter (num_H4 = 3  )
	parameter (num_He = 4  )
	parameter (num_Li = 5  )
	parameter (num_C  = 6  )
	parameter (num_N  = 7  )
	parameter (num_O  = 8  )
	parameter (num_F  = 9  )
	parameter (num_Ne  =10 )
	parameter (num_Al = 11 )
	parameter (num_Si = 12 )
	parameter (num_Ar = 13 )
	parameter (num_Kr = 14 )
	parameter (num_Xe = 15 )
	parameter (num_C1  = 16 )	! C in CO2
	parameter (num_C2  = 17 )	! C in CF4
	parameter (num_C3  = 18 )	! C in CH4
*** Additions (RV 20/9/99).
        integer num_S
        parameter (num_S = 19)
*** End of additions.

	integer num

c	character*1 a
c	integer i,z,n,k

	qash=0


c	The next code is generated
c	by a computer program
c	using a readable data file



	if(zato.eq.1)then
c		if(num.eq.num_H)then
			qash=1
			athreshold(1)=1e-05
			aweight(1)=1
c		endif
		if(num.eq.num_H3)then	! for CH4
			qash=1
			athreshold(1)=15.2e-06
			aweight(1)=1
		endif
	endif
	if(zato.eq.2)then
	qash=1
	athreshold(1)=1.36129e-05
	aweight(1)=1
	endif
	if(zato.eq.3)then
	qash=2
	athreshold(1)=5.44515e-05
	aweight(1)=0.666667
	athreshold(2)=1e-05
	aweight(2)=0.333333
	endif
	if(zato.eq.4)then
	qash=2
	athreshold(1)=0.000123
	aweight(1)=0.5
	athreshold(2)=1e-05
	aweight(2)=0.5
	endif
	if(zato.eq.5)then
	qash=2
	athreshold(1)=0.000218
	aweight(1)=0.4
	athreshold(2)=1e-05
	aweight(2)=0.6
	endif
	if(zato.eq.6)then
	qash=2
	athreshold(1)=0.00034
	aweight(1)=0.333333
	athreshold(2)=1.36129e-05
	aweight(2)=0.666667
	endif
	if(zato.eq.7)then
	qash=2
	athreshold(1)=0.00049
	aweight(1)=0.285714
	athreshold(2)=2.12701e-05
	aweight(2)=0.714286
	endif
	if(zato.eq.8)then
	qash=2
	athreshold(1)=0.000667
	aweight(1)=0.25
	athreshold(2)=3.0629e-05
	aweight(2)=0.75
	endif
	if(zato.eq.9)then
	qash=2
	athreshold(1)=0.000871
	aweight(1)=0.222222
	athreshold(2)=4.16894e-05
	aweight(2)=0.777778
	endif
	if(zato.eq.10)then
	qash=2
	athreshold(1)=0.001103
	aweight(1)=0.2
	athreshold(2)=5.44515e-05
	aweight(2)=0.8
	endif
	if(zato.eq.11)then
	qash=3
	athreshold(1)=0.001361
	aweight(1)=0.181818
	athreshold(2)=8.50804e-05
	aweight(2)=0.727273
	athreshold(3)=1e-05
	aweight(3)=0.090909
	endif
	if(zato.eq.12)then
	qash=3
	athreshold(1)=0.001647
	aweight(1)=0.166667
	athreshold(2)=0.000123
	aweight(2)=0.666667
	athreshold(3)=1e-05
	aweight(3)=0.166667
	endif
	if(zato.eq.13)then
	qash=3
	athreshold(1)=0.00196
	aweight(1)=0.153846
	athreshold(2)=0.000167
	aweight(2)=0.615385
	athreshold(3)=1e-05
	aweight(3)=0.230769
	endif
	if(zato.eq.14)then
	qash=3
	athreshold(1)=0.002301
	aweight(1)=0.142857
	athreshold(2)=0.000218
	aweight(2)=0.571429
	athreshold(3)=1e-05
	aweight(3)=0.285714
	endif
	if(zato.eq.15)then
	qash=3
	athreshold(1)=0.002668
	aweight(1)=0.133333
	athreshold(2)=0.000276
	aweight(2)=0.533333
	athreshold(3)=1e-05
	aweight(3)=0.333333
	endif
	if(zato.eq.16)then
	qash=3
	athreshold(1)=0.003063
	aweight(1)=0.125
	athreshold(2)=0.00034
	aweight(2)=0.5
	athreshold(3)=1.36129e-05
	aweight(3)=0.375
	endif
	if(zato.eq.17)then
	qash=3
	athreshold(1)=0.003485
	aweight(1)=0.117647
	athreshold(2)=0.000412
	aweight(2)=0.470588
	athreshold(3)=1.85286e-05
	aweight(3)=0.411765
	endif
	if(zato.eq.18)then
	qash=3
	athreshold(1)=0.003934
	aweight(1)=0.111111
	athreshold(2)=0.00049
	aweight(2)=0.444444
	athreshold(3)=2.42007e-05
	aweight(3)=0.444444
	endif
	if(zato.eq.19)then
	qash=4
	athreshold(1)=0.004411
	aweight(1)=0.105263
	athreshold(2)=0.000575
	aweight(2)=0.421053
	athreshold(3)=3.78135e-05
	aweight(3)=0.421053
	athreshold(4)=1e-05
	aweight(4)=0.052632
	endif
	if(zato.eq.20)then
	qash=4
	athreshold(1)=0.004914
	aweight(1)=0.1
	athreshold(2)=0.000667
	aweight(2)=0.4
	athreshold(3)=5.44515e-05
	aweight(3)=0.4
	athreshold(4)=1e-05
	aweight(4)=0.1
	endif
	if(zato.eq.21)then
	qash=4
	athreshold(1)=0.005445
	aweight(1)=0.095238
	athreshold(2)=0.000766
	aweight(2)=0.380952
	athreshold(3)=7.41145e-05
	aweight(3)=0.380952
	athreshold(4)=1e-05
	aweight(4)=0.142857
	endif
	if(zato.eq.22)then
	qash=4
	athreshold(1)=0.006003
	aweight(1)=0.090909
	athreshold(2)=0.000871
	aweight(2)=0.363636
	athreshold(3)=9.68026e-05
	aweight(3)=0.363636
	athreshold(4)=1e-05
	aweight(4)=0.181818
	endif
	if(zato.eq.23)then
	qash=4
	athreshold(1)=0.006589
	aweight(1)=0.086957
	athreshold(2)=0.000984
	aweight(2)=0.347826
	athreshold(3)=0.000123
	aweight(3)=0.347826
	athreshold(4)=1e-05
	aweight(4)=0.217391
	endif
	if(zato.eq.24)then
	qash=4
	athreshold(1)=0.007201
	aweight(1)=0.083333
	athreshold(2)=0.001103
	aweight(2)=0.333333
	athreshold(3)=0.000151
	aweight(3)=0.333333
	athreshold(4)=1e-05
	aweight(4)=0.25
	endif
	if(zato.eq.25)then
	qash=4
	athreshold(1)=0.007841
	aweight(1)=0.08
	athreshold(2)=0.001229
	aweight(2)=0.32
	athreshold(3)=0.000183
	aweight(3)=0.32
	athreshold(4)=1.04224e-05
	aweight(4)=0.28
	endif
	if(zato.eq.26)then
	qash=4
	athreshold(1)=0.008508
	aweight(1)=0.076923
	athreshold(2)=0.001361
	aweight(2)=0.307692
	athreshold(3)=0.000218
	aweight(3)=0.307692
	athreshold(4)=1.36129e-05
	aweight(4)=0.307692
	endif
	if(zato.eq.27)then
	qash=4
	athreshold(1)=0.009202
	aweight(1)=0.074074
	athreshold(2)=0.001501
	aweight(2)=0.296296
	athreshold(3)=0.000256
	aweight(3)=0.296296
	athreshold(4)=1.72288e-05
	aweight(4)=0.333333
	endif
	if(zato.eq.28)then
	qash=4
	athreshold(1)=0.009924
	aweight(1)=0.071429
	athreshold(2)=0.001647
	aweight(2)=0.285714
	athreshold(3)=0.000296
	aweight(3)=0.285714
	athreshold(4)=2.12701e-05
	aweight(4)=0.357143
	endif
	if(zato.eq.29)then
	qash=4
	athreshold(1)=0.010672
	aweight(1)=0.068966
	athreshold(2)=0.0018
	aweight(2)=0.275862
	athreshold(3)=0.00034
	aweight(3)=0.275862
	athreshold(4)=2.57368e-05
	aweight(4)=0.37931
	endif
	if(zato.eq.30)then
	qash=4
	athreshold(1)=0.011448
	aweight(1)=0.066667
	athreshold(2)=0.00196
	aweight(2)=0.266667
	athreshold(3)=0.000387
	aweight(3)=0.266667
	athreshold(4)=3.0629e-05
	aweight(4)=0.4
	endif
	if(zato.eq.31)then
	qash=4
	athreshold(1)=0.012252
	aweight(1)=0.064516
	athreshold(2)=0.002127
	aweight(2)=0.258065
	athreshold(3)=0.000437
	aweight(3)=0.258065
	athreshold(4)=3.59465e-05
	aweight(4)=0.419355
	endif
	if(zato.eq.32)then
	qash=4
	athreshold(1)=0.013082
	aweight(1)=0.0625
	athreshold(2)=0.002301
	aweight(2)=0.25
	athreshold(3)=0.00049
	aweight(3)=0.25
	athreshold(4)=4.16894e-05
	aweight(4)=0.4375
	endif
	if(zato.eq.33)then
	qash=4
	athreshold(1)=0.01394
	aweight(1)=0.060606
	athreshold(2)=0.002481
	aweight(2)=0.242424
	athreshold(3)=0.000546
	aweight(3)=0.242424
	athreshold(4)=4.78577e-05
	aweight(4)=0.454545
	endif
	if(zato.eq.34)then
	qash=4
	athreshold(1)=0.014824
	aweight(1)=0.058824
	athreshold(2)=0.002668
	aweight(2)=0.235294
	athreshold(3)=0.000605
	aweight(3)=0.235294
	athreshold(4)=5.44515e-05
	aweight(4)=0.470588
	endif
	if(zato.eq.35)then
	qash=4
	athreshold(1)=0.015736
	aweight(1)=0.057143
	athreshold(2)=0.002862
	aweight(2)=0.228571
	athreshold(3)=0.000667
	aweight(3)=0.228571
	athreshold(4)=6.14706e-05
	aweight(4)=0.485714
	endif
	if(zato.eq.36)then
	qash=4
	athreshold(1)=0.016676
	aweight(1)=0.055556
	athreshold(2)=0.003063
	aweight(2)=0.222222
	athreshold(3)=0.000732
	aweight(3)=0.222222
	athreshold(4)=6.89152e-05
	aweight(4)=0.5
	endif
	if(zato.eq.37)then
	qash=5
	athreshold(1)=0.017642
	aweight(1)=0.054054
	athreshold(2)=0.00327
	aweight(2)=0.216216
	athreshold(3)=0.0008
	aweight(3)=0.216216
	athreshold(4)=8.50804e-05
	aweight(4)=0.486486
	athreshold(5)=1e-05
	aweight(5)=0.027027
	endif
	if(zato.eq.38)then
	qash=5
	athreshold(1)=0.018636
	aweight(1)=0.052632
	athreshold(2)=0.003485
	aweight(2)=0.210526
	athreshold(3)=0.000871
	aweight(3)=0.210526
	athreshold(4)=0.000103
	aweight(4)=0.473684
	athreshold(5)=1e-05
	aweight(5)=0.052632
	endif
	if(zato.eq.39)then
	qash=5
	athreshold(1)=0.019657
	aweight(1)=0.051282
	athreshold(2)=0.003706
	aweight(2)=0.205128
	athreshold(3)=0.000945
	aweight(3)=0.205128
	athreshold(4)=0.000123
	aweight(4)=0.461538
	athreshold(5)=1e-05
	aweight(5)=0.076923
	endif
	if(zato.eq.40)then
	qash=5
	athreshold(1)=0.020705
	aweight(1)=0.05
	athreshold(2)=0.003934
	aweight(2)=0.2
	athreshold(3)=0.001022
	aweight(3)=0.2
	athreshold(4)=0.000144
	aweight(4)=0.45
	athreshold(5)=1e-05
	aweight(5)=0.1
	endif
	if(zato.eq.41)then
	qash=5
	athreshold(1)=0.021781
	aweight(1)=0.04878
	athreshold(2)=0.004169
	aweight(2)=0.195122
	athreshold(3)=0.001103
	aweight(3)=0.195122
	athreshold(4)=0.000167
	aweight(4)=0.439024
	athreshold(5)=1e-05
	aweight(5)=0.121951
	endif
	if(zato.eq.42)then
	qash=5
	athreshold(1)=0.022883
	aweight(1)=0.047619
	athreshold(2)=0.004411
	aweight(2)=0.190476
	athreshold(3)=0.001186
	aweight(3)=0.190476
	athreshold(4)=0.000191
	aweight(4)=0.428571
	athreshold(5)=1e-05
	aweight(5)=0.142857
	endif
	if(zato.eq.43)then
	qash=5
	athreshold(1)=0.024013
	aweight(1)=0.046512
	athreshold(2)=0.004659
	aweight(2)=0.186047
	athreshold(3)=0.001272
	aweight(3)=0.186047
	athreshold(4)=0.000218
	aweight(4)=0.418605
	athreshold(5)=1e-05
	aweight(5)=0.162791
	endif
	if(zato.eq.44)then
	qash=5
	athreshold(1)=0.02517
	aweight(1)=0.045455
	athreshold(2)=0.004914
	aweight(2)=0.181818
	athreshold(3)=0.001361
	aweight(3)=0.181818
	athreshold(4)=0.000246
	aweight(4)=0.409091
	athreshold(5)=1e-05
	aweight(5)=0.181818
	endif
	if(zato.eq.45)then
	qash=5
	athreshold(1)=0.026355
	aweight(1)=0.044444
	athreshold(2)=0.005176
	aweight(2)=0.177778
	athreshold(3)=0.001454
	aweight(3)=0.177778
	athreshold(4)=0.000276
	aweight(4)=0.4
	athreshold(5)=1.10264e-05
	aweight(5)=0.2
	endif
	if(zato.eq.46)then
	qash=5
	athreshold(1)=0.027566
	aweight(1)=0.043478
	athreshold(2)=0.005445
	aweight(2)=0.173913
	athreshold(3)=0.001549
	aweight(3)=0.173913
	athreshold(4)=0.000307
	aweight(4)=0.391304
	athreshold(5)=1.36129e-05
	aweight(5)=0.217391
	endif
	if(zato.eq.47)then
	qash=5
	athreshold(1)=0.028805
	aweight(1)=0.042553
	athreshold(2)=0.005721
	aweight(2)=0.170213
	athreshold(3)=0.001647
	aweight(3)=0.170213
	athreshold(4)=0.00034
	aweight(4)=0.382979
	athreshold(5)=1.64716e-05
	aweight(5)=0.234043
	endif
	if(zato.eq.48)then
	qash=5
	athreshold(1)=0.030071
	aweight(1)=0.041667
	athreshold(2)=0.006003
	aweight(2)=0.166667
	athreshold(3)=0.001748
	aweight(3)=0.166667
	athreshold(4)=0.000375
	aweight(4)=0.375
	athreshold(5)=1.96025e-05
	aweight(5)=0.25
	endif
	if(zato.eq.49)then
	qash=5
	athreshold(1)=0.031364
	aweight(1)=0.040816
	athreshold(2)=0.006293
	aweight(2)=0.163265
	athreshold(3)=0.001853
	aweight(3)=0.163265
	athreshold(4)=0.000412
	aweight(4)=0.367347
	athreshold(5)=2.30058e-05
	aweight(5)=0.265306
	endif
	if(zato.eq.50)then
	qash=5
	athreshold(1)=0.032685
	aweight(1)=0.04
	athreshold(2)=0.006589
	aweight(2)=0.16
	athreshold(3)=0.00196
	aweight(3)=0.16
	athreshold(4)=0.00045
	aweight(4)=0.36
	athreshold(5)=2.66812e-05
	aweight(5)=0.28
	endif
	if(zato.eq.51)then
	qash=5
	athreshold(1)=0.034032
	aweight(1)=0.039216
	athreshold(2)=0.006892
	aweight(2)=0.156863
	athreshold(3)=0.002071
	aweight(3)=0.156863
	athreshold(4)=0.00049
	aweight(4)=0.352941
	athreshold(5)=3.0629e-05
	aweight(5)=0.294118
	endif
	if(zato.eq.52)then
	qash=5
	athreshold(1)=0.035407
	aweight(1)=0.038462
	athreshold(2)=0.007201
	aweight(2)=0.153846
	athreshold(3)=0.002184
	aweight(3)=0.153846
	athreshold(4)=0.000532
	aweight(4)=0.346154
	athreshold(5)=3.48489e-05
	aweight(5)=0.307692
	endif
	if(zato.eq.53)then
	qash=5
	athreshold(1)=0.036809
	aweight(1)=0.037736
	athreshold(2)=0.007518
	aweight(2)=0.150943
	athreshold(3)=0.002301
	aweight(3)=0.150943
	athreshold(4)=0.000575
	aweight(4)=0.339623
	athreshold(5)=3.93412e-05
	aweight(5)=0.320755
	endif
	if(zato.eq.54)then
	qash=5
	athreshold(1)=0.038239
	aweight(1)=0.037037
	athreshold(2)=0.007841
	aweight(2)=0.148148
	athreshold(3)=0.00242
	aweight(3)=0.148148
	athreshold(4)=0.00062
	aweight(4)=0.333333
	athreshold(5)=4.41057e-05
	aweight(5)=0.333333
	endif
	if(zato.eq.55)then
	qash=5
	athreshold(1)=0.039695
	aweight(1)=0.036364
	athreshold(2)=0.008171
	aweight(2)=0.145455
	athreshold(3)=0.002543
	aweight(3)=0.145455
	athreshold(4)=0.000667
	aweight(4)=0.327273
	athreshold(5)=4.91425e-05
	aweight(5)=0.345455
	endif
	if(zato.eq.56)then
	qash=5
	athreshold(1)=0.041179
	aweight(1)=0.035714
	athreshold(2)=0.008508
	aweight(2)=0.142857
	athreshold(3)=0.002668
	aweight(3)=0.142857
	athreshold(4)=0.000716
	aweight(4)=0.321429
	athreshold(5)=5.44515e-05
	aweight(5)=0.357143
	endif
	if(zato.eq.57)then
	qash=5
	athreshold(1)=0.04269
	aweight(1)=0.035088
	athreshold(2)=0.008852
	aweight(2)=0.140351
	athreshold(3)=0.002797
	aweight(3)=0.140351
	athreshold(4)=0.000766
	aweight(4)=0.315789
	athreshold(5)=6.00328e-05
	aweight(5)=0.368421
	endif
	if(zato.eq.58)then
	qash=5
	athreshold(1)=0.044228
	aweight(1)=0.034483
	athreshold(2)=0.009202
	aweight(2)=0.137931
	athreshold(3)=0.002928
	aweight(3)=0.137931
	athreshold(4)=0.000818
	aweight(4)=0.310345
	athreshold(5)=6.58863e-05
	aweight(5)=0.37931
	endif
	if(zato.eq.59)then
	qash=6
	athreshold(1)=0.045794
	aweight(1)=0.033898
	athreshold(2)=0.00956
	aweight(2)=0.135593
	athreshold(3)=0.003063
	aweight(3)=0.135593
	athreshold(4)=0.000871
	aweight(4)=0.305085
	athreshold(5)=7.84101e-05
	aweight(5)=0.372881
	athreshold(6)=1e-05
	aweight(6)=0.016949
	endif
	if(zato.eq.60)then
	qash=6
	athreshold(1)=0.047386
	aweight(1)=0.033333
	athreshold(2)=0.009924
	aweight(2)=0.133333
	athreshold(3)=0.003201
	aweight(3)=0.133333
	athreshold(4)=0.000927
	aweight(4)=0.3
	athreshold(5)=9.2023e-05
	aweight(5)=0.366667
	athreshold(6)=1e-05
	aweight(6)=0.033333
	endif
	if(zato.eq.61)then
	qash=6
	athreshold(1)=0.049006
	aweight(1)=0.032787
	athreshold(2)=0.010295
	aweight(2)=0.131148
	athreshold(3)=0.003341
	aweight(3)=0.131148
	athreshold(4)=0.000984
	aweight(4)=0.295082
	athreshold(5)=0.000107
	aweight(5)=0.360656
	athreshold(6)=1e-05
	aweight(6)=0.04918
	endif
	if(zato.eq.62)then
	qash=6
	athreshold(1)=0.050653
	aweight(1)=0.032258
	athreshold(2)=0.010672
	aweight(2)=0.129032
	athreshold(3)=0.003485
	aweight(3)=0.129032
	athreshold(4)=0.001042
	aweight(4)=0.290323
	athreshold(5)=0.000123
	aweight(5)=0.354839
	athreshold(6)=1e-05
	aweight(6)=0.064516
	endif
	if(zato.eq.63)then
	qash=6
	athreshold(1)=0.052328
	aweight(1)=0.031746
	athreshold(2)=0.011057
	aweight(2)=0.126984
	athreshold(3)=0.003632
	aweight(3)=0.126984
	athreshold(4)=0.001103
	aweight(4)=0.285714
	athreshold(5)=0.000139
	aweight(5)=0.349206
	athreshold(6)=1e-05
	aweight(6)=0.079365
	endif
	if(zato.eq.64)then
	qash=6
	athreshold(1)=0.054029
	aweight(1)=0.03125
	athreshold(2)=0.011448
	aweight(2)=0.125
	athreshold(3)=0.003781
	aweight(3)=0.125
	athreshold(4)=0.001165
	aweight(4)=0.28125
	athreshold(5)=0.000157
	aweight(5)=0.34375
	athreshold(6)=1e-05
	aweight(6)=0.09375
	endif
	if(zato.eq.65)then
	qash=6
	athreshold(1)=0.055758
	aweight(1)=0.030769
	athreshold(2)=0.011847
	aweight(2)=0.123077
	athreshold(3)=0.003934
	aweight(3)=0.123077
	athreshold(4)=0.001229
	aweight(4)=0.276923
	athreshold(5)=0.000176
	aweight(5)=0.338462
	athreshold(6)=1e-05
	aweight(6)=0.107692
	endif
	if(zato.eq.66)then
	qash=6
	athreshold(1)=0.057514
	aweight(1)=0.030303
	athreshold(2)=0.012252
	aweight(2)=0.121212
	athreshold(3)=0.00409
	aweight(3)=0.121212
	athreshold(4)=0.001294
	aweight(4)=0.272727
	athreshold(5)=0.000197
	aweight(5)=0.333333
	athreshold(6)=1e-05
	aweight(6)=0.121212
	endif
	if(zato.eq.67)then
	qash=6
	athreshold(1)=0.059298
	aweight(1)=0.029851
	athreshold(2)=0.012663
	aweight(2)=0.119403
	athreshold(3)=0.004249
	aweight(3)=0.119403
	athreshold(4)=0.001361
	aweight(4)=0.268657
	athreshold(5)=0.000218
	aweight(5)=0.328358
	athreshold(6)=1e-05
	aweight(6)=0.134328
	endif
	if(zato.eq.68)then
	qash=6
	athreshold(1)=0.061108
	aweight(1)=0.029412
	athreshold(2)=0.013082
	aweight(2)=0.117647
	athreshold(3)=0.004411
	aweight(3)=0.117647
	athreshold(4)=0.00143
	aweight(4)=0.264706
	athreshold(5)=0.00024
	aweight(5)=0.323529
	athreshold(6)=1e-05
	aweight(6)=0.147059
	endif
	if(zato.eq.69)then
	qash=6
	athreshold(1)=0.062946
	aweight(1)=0.028986
	athreshold(2)=0.013507
	aweight(2)=0.115942
	athreshold(3)=0.004575
	aweight(3)=0.115942
	athreshold(4)=0.001501
	aweight(4)=0.26087
	athreshold(5)=0.000264
	aweight(5)=0.318841
	athreshold(6)=1.14386e-05
	aweight(6)=0.15942
	endif
	if(zato.eq.70)then
	qash=6
	athreshold(1)=0.064811
	aweight(1)=0.028571
	athreshold(2)=0.01394
	aweight(2)=0.114286
	athreshold(3)=0.004743
	aweight(3)=0.114286
	athreshold(4)=0.001573
	aweight(4)=0.257143
	athreshold(5)=0.000288
	aweight(5)=0.314286
	athreshold(6)=1.36129e-05
	aweight(6)=0.171429
	endif
	if(zato.eq.71)then
	qash=6
	athreshold(1)=0.066703
	aweight(1)=0.028169
	athreshold(2)=0.014379
	aweight(2)=0.112676
	athreshold(3)=0.004914
	aweight(3)=0.112676
	athreshold(4)=0.001647
	aweight(4)=0.253521
	athreshold(5)=0.000314
	aweight(5)=0.309859
	athreshold(6)=1.59762e-05
	aweight(6)=0.183099
	endif
	if(zato.eq.72)then
	qash=6
	athreshold(1)=0.068622
	aweight(1)=0.027778
	athreshold(2)=0.014824
	aweight(2)=0.111111
	athreshold(3)=0.005088
	aweight(3)=0.111111
	athreshold(4)=0.001723
	aweight(4)=0.25
	athreshold(5)=0.00034
	aweight(5)=0.305556
	athreshold(6)=1.85286e-05
	aweight(6)=0.194444
	endif
	if(zato.eq.73)then
	qash=6
	athreshold(1)=0.070569
	aweight(1)=0.027397
	athreshold(2)=0.015277
	aweight(2)=0.109589
	athreshold(3)=0.005265
	aweight(3)=0.109589
	athreshold(4)=0.0018
	aweight(4)=0.246575
	athreshold(5)=0.000368
	aweight(5)=0.30137
	athreshold(6)=2.12701e-05
	aweight(6)=0.205479
	endif
	if(zato.eq.74)then
	qash=6
	athreshold(1)=0.072543
	aweight(1)=0.027027
	athreshold(2)=0.015736
	aweight(2)=0.108108
	athreshold(3)=0.005445
	aweight(3)=0.108108
	athreshold(4)=0.001879
	aweight(4)=0.243243
	athreshold(5)=0.000397
	aweight(5)=0.297297
	athreshold(6)=2.42007e-05
	aweight(6)=0.216216
	endif
	if(zato.eq.75)then
	qash=6
	athreshold(1)=0.074544
	aweight(1)=0.026667
	athreshold(2)=0.016203
	aweight(2)=0.106667
	athreshold(3)=0.005628
	aweight(3)=0.106667
	athreshold(4)=0.00196
	aweight(4)=0.24
	athreshold(5)=0.000427
	aweight(5)=0.293333
	athreshold(6)=2.73203e-05
	aweight(6)=0.226667
	endif
	if(zato.eq.76)then
	qash=6
	athreshold(1)=0.076572
	aweight(1)=0.026316
	athreshold(2)=0.016676
	aweight(2)=0.105263
	athreshold(3)=0.005814
	aweight(3)=0.105263
	athreshold(4)=0.002043
	aweight(4)=0.236842
	athreshold(5)=0.000458
	aweight(5)=0.289474
	athreshold(6)=3.0629e-05
	aweight(6)=0.236842
	endif
	if(zato.eq.77)then
	qash=6
	athreshold(1)=0.078628
	aweight(1)=0.025974
	athreshold(2)=0.017156
	aweight(2)=0.103896
	athreshold(3)=0.006003
	aweight(3)=0.103896
	athreshold(4)=0.002127
	aweight(4)=0.233766
	athreshold(5)=0.00049
	aweight(5)=0.285714
	athreshold(6)=3.41267e-05
	aweight(6)=0.246753
	endif
	if(zato.eq.78)then
	qash=6
	athreshold(1)=0.080711
	aweight(1)=0.025641
	athreshold(2)=0.017642
	aweight(2)=0.102564
	athreshold(3)=0.006195
	aweight(3)=0.102564
	athreshold(4)=0.002213
	aweight(4)=0.230769
	athreshold(5)=0.000523
	aweight(5)=0.282051
	athreshold(6)=3.78135e-05
	aweight(6)=0.25641
	endif
	if(zato.eq.79)then
	qash=6
	athreshold(1)=0.082821
	aweight(1)=0.025316
	athreshold(2)=0.018136
	aweight(2)=0.101266
	athreshold(3)=0.00639
	aweight(3)=0.101266
	athreshold(4)=0.002301
	aweight(4)=0.227848
	athreshold(5)=0.000558
	aweight(5)=0.278481
	athreshold(6)=4.16894e-05
	aweight(6)=0.265823
	endif
	if(zato.eq.80)then
	qash=6
	athreshold(1)=0.084958
	aweight(1)=0.025
	athreshold(2)=0.018636
	aweight(2)=0.1
	athreshold(3)=0.006589
	aweight(3)=0.1
	athreshold(4)=0.00239
	aweight(4)=0.225
	athreshold(5)=0.000593
	aweight(5)=0.275
	athreshold(6)=4.57544e-05
	aweight(6)=0.275
	endif
	if(zato.eq.81)then
	qash=6
	athreshold(1)=0.087122
	aweight(1)=0.024691
	athreshold(2)=0.019143
	aweight(2)=0.098765
	athreshold(3)=0.00679
	aweight(3)=0.098765
	athreshold(4)=0.002481
	aweight(4)=0.222222
	athreshold(5)=0.000629
	aweight(5)=0.271605
	athreshold(6)=5.00084e-05
	aweight(6)=0.283951
	endif
	if(zato.eq.82)then
	qash=6
	athreshold(1)=0.089314
	aweight(1)=0.02439
	athreshold(2)=0.019657
	aweight(2)=0.097561
	athreshold(3)=0.006994
	aweight(3)=0.097561
	athreshold(4)=0.002574
	aweight(4)=0.219512
	athreshold(5)=0.000667
	aweight(5)=0.268293
	athreshold(6)=5.44515e-05
	aweight(6)=0.292683
	endif
	if(zato.eq.83)then
	qash=6
	athreshold(1)=0.091533
	aweight(1)=0.024096
	athreshold(2)=0.020178
	aweight(2)=0.096386
	athreshold(3)=0.007201
	aweight(3)=0.096386
	athreshold(4)=0.002668
	aweight(4)=0.216867
	athreshold(5)=0.000706
	aweight(5)=0.26506
	athreshold(6)=5.90836e-05
	aweight(6)=0.301205
	endif
	if(zato.eq.84)then
	qash=6
	athreshold(1)=0.093779
	aweight(1)=0.02381
	athreshold(2)=0.020705
	aweight(2)=0.095238
	athreshold(3)=0.007411
	aweight(3)=0.095238
	athreshold(4)=0.002764
	aweight(4)=0.214286
	athreshold(5)=0.000745
	aweight(5)=0.261905
	athreshold(6)=6.39049e-05
	aweight(6)=0.309524
	endif
	if(zato.eq.85)then
	qash=6
	athreshold(1)=0.096052
	aweight(1)=0.023529
	athreshold(2)=0.021239
	aweight(2)=0.094118
	athreshold(3)=0.007625
	aweight(3)=0.094118
	athreshold(4)=0.002862
	aweight(4)=0.211765
	athreshold(5)=0.000786
	aweight(5)=0.258824
	athreshold(6)=6.89152e-05
	aweight(6)=0.317647
	endif
	if(zato.eq.86)then
	qash=6
	athreshold(1)=0.098353
	aweight(1)=0.023256
	athreshold(2)=0.021781
	aweight(2)=0.093023
	athreshold(3)=0.007841
	aweight(3)=0.093023
	athreshold(4)=0.002962
	aweight(4)=0.209302
	athreshold(5)=0.000828
	aweight(5)=0.255814
	athreshold(6)=7.41145e-05
	aweight(6)=0.325581
	endif
	if(zato.eq.87)then
	qash=6
	athreshold(1)=0.100681
	aweight(1)=0.022989
	athreshold(2)=0.022329
	aweight(2)=0.091954
	athreshold(3)=0.00806
	aweight(3)=0.091954
	athreshold(4)=0.003063
	aweight(4)=0.206897
	athreshold(5)=0.000871
	aweight(5)=0.252874
	athreshold(6)=7.9503e-05
	aweight(6)=0.333333
	endif
	if(zato.eq.88)then
	qash=6
	athreshold(1)=0.103036
	aweight(1)=0.022727
	athreshold(2)=0.022883
	aweight(2)=0.090909
	athreshold(3)=0.008283
	aweight(3)=0.090909
	athreshold(4)=0.003166
	aweight(4)=0.204545
	athreshold(5)=0.000915
	aweight(5)=0.25
	athreshold(6)=8.50804e-05
	aweight(6)=0.340909
	endif
	if(zato.eq.89)then
	qash=6
	athreshold(1)=0.105418
	aweight(1)=0.022472
	athreshold(2)=0.023445
	aweight(2)=0.089888
	athreshold(3)=0.008508
	aweight(3)=0.089888
	athreshold(4)=0.00327
	aweight(4)=0.202247
	athreshold(5)=0.000961
	aweight(5)=0.247191
	athreshold(6)=9.0847e-05
	aweight(6)=0.348315
	endif
	if(zato.eq.90)then
	qash=6
	athreshold(1)=0.107828
	aweight(1)=0.022222
	athreshold(2)=0.024013
	aweight(2)=0.088889
	athreshold(3)=0.008736
	aweight(3)=0.088889
	athreshold(4)=0.003377
	aweight(4)=0.2
	athreshold(5)=0.001007
	aweight(5)=0.244444
	athreshold(6)=9.68026e-05
	aweight(6)=0.355556
	endif
	if(zato.eq.91)then
	qash=7
	athreshold(1)=0.110264
	aweight(1)=0.021978
	athreshold(2)=0.024588
	aweight(2)=0.087912
	athreshold(3)=0.008968
	aweight(3)=0.087912
	athreshold(4)=0.003485
	aweight(4)=0.197802
	athreshold(5)=0.001054
	aweight(5)=0.241758
	athreshold(6)=0.000109
	aweight(6)=0.351648
	athreshold(7)=1e-05
	aweight(7)=0.010989
	endif
	if(zato.eq.92)then
	qash=7
	athreshold(1)=0.112728
	aweight(1)=0.021739
	athreshold(2)=0.02517
	aweight(2)=0.086957
	athreshold(3)=0.009202
	aweight(3)=0.086957
	athreshold(4)=0.003595
	aweight(4)=0.195652
	athreshold(5)=0.001103
	aweight(5)=0.23913
	athreshold(6)=0.000123
	aweight(6)=0.347826
	athreshold(7)=1e-05
	aweight(7)=0.021739
	endif
	if(zato.eq.93)then
	qash=7
	athreshold(1)=0.115219
	aweight(1)=0.021505
	athreshold(2)=0.025759
	aweight(2)=0.086022
	athreshold(3)=0.00944
	aweight(3)=0.086022
	athreshold(4)=0.003706
	aweight(4)=0.193548
	athreshold(5)=0.001152
	aweight(5)=0.236559
	athreshold(6)=0.000137
	aweight(6)=0.344086
	athreshold(7)=1e-05
	aweight(7)=0.032258
	endif
	if(zato.eq.94)then
	qash=7
	athreshold(1)=0.117738
	aweight(1)=0.021277
	athreshold(2)=0.026355
	aweight(2)=0.085106
	athreshold(3)=0.00968
	aweight(3)=0.085106
	athreshold(4)=0.003819
	aweight(4)=0.191489
	athreshold(5)=0.001203
	aweight(5)=0.234043
	athreshold(6)=0.000151
	aweight(6)=0.340426
	athreshold(7)=1e-05
	aweight(7)=0.042553
	endif
	if(zato.eq.95)then
	qash=7
	athreshold(1)=0.120283
	aweight(1)=0.021053
	athreshold(2)=0.026957
	aweight(2)=0.084211
	athreshold(3)=0.009924
	aweight(3)=0.084211
	athreshold(4)=0.003934
	aweight(4)=0.189474
	athreshold(5)=0.001255
	aweight(5)=0.231579
	athreshold(6)=0.000167
	aweight(6)=0.336842
	athreshold(7)=1e-05
	aweight(7)=0.052632
	endif
	if(zato.eq.96)then
	qash=7
	athreshold(1)=0.122856
	aweight(1)=0.020833
	athreshold(2)=0.027566
	aweight(2)=0.083333
	athreshold(3)=0.01017
	aweight(3)=0.083333
	athreshold(4)=0.004051
	aweight(4)=0.1875
	athreshold(5)=0.001307
	aweight(5)=0.229167
	athreshold(6)=0.000183
	aweight(6)=0.333333
	athreshold(7)=1e-05
	aweight(7)=0.0625
	endif
	if(zato.eq.97)then
	qash=7
	athreshold(1)=0.125456
	aweight(1)=0.020619
	athreshold(2)=0.028182
	aweight(2)=0.082474
	athreshold(3)=0.01042
	aweight(3)=0.082474
	athreshold(4)=0.004169
	aweight(4)=0.185567
	athreshold(5)=0.001361
	aweight(5)=0.226804
	athreshold(6)=0.0002
	aweight(6)=0.329897
	athreshold(7)=1e-05
	aweight(7)=0.072165
	endif
	if(zato.eq.98)then
	qash=7
	athreshold(1)=0.128084
	aweight(1)=0.020408
	athreshold(2)=0.028805
	aweight(2)=0.081633
	athreshold(3)=0.010672
	aweight(3)=0.081633
	athreshold(4)=0.004289
	aweight(4)=0.183673
	athreshold(5)=0.001416
	aweight(5)=0.22449
	athreshold(6)=0.000218
	aweight(6)=0.326531
	athreshold(7)=1e-05
	aweight(7)=0.081633
	endif
	if(zato.eq.99)then
	qash=7
	athreshold(1)=0.130738
	aweight(1)=0.020202
	athreshold(2)=0.029434
	aweight(2)=0.080808
	athreshold(3)=0.010928
	aweight(3)=0.080808
	athreshold(4)=0.004411
	aweight(4)=0.181818
	athreshold(5)=0.001472
	aweight(5)=0.222222
	athreshold(6)=0.000236
	aweight(6)=0.323232
	athreshold(7)=1e-05
	aweight(7)=0.090909
	endif
	if(zato.eq.100)then
	qash=7
	athreshold(1)=0.13342
	aweight(1)=0.02
	athreshold(2)=0.030071
	aweight(2)=0.08
	athreshold(3)=0.011187
	aweight(3)=0.08
	athreshold(4)=0.004534
	aweight(4)=0.18
	athreshold(5)=0.00153
	aweight(5)=0.22
	athreshold(6)=0.000256
	aweight(6)=0.32
	athreshold(7)=1e-05
	aweight(7)=0.1
	endif


c	end of genetared code


c	call prishellfi

	end


	subroutine prishellfi

	implicit none

c         include 'GoEvent.inc'
c      Main control variables


	integer soo		   ! Flag, allowing to print
				   !  to stream 'oo'
				   ! If it is 0, no print will be at all,
				   ! except the case of serious problems.
	integer oo		   ! The output stream logical number.
	integer qevt		   ! Quantity of events to produce.
	integer nevt		   ! Current number of the event.
	integer ninfo		   ! Quantity of the first events
				   ! to print debug info.
	integer ssimioni	   ! Flag to simulate ionization loss,
				   ! 0 - no ionization,
				   ! 1 - to simulate ionization.
				   !
				   !
				   !
	integer srandoff	   ! Flag to swich off the randomization
				   ! in function treatdel.
				   ! It is for debug and without guarantee.
	parameter (srandoff=0)	   ! Normal regim with randommization.

	integer pqup		   ! dimensions of arrays of auxiliary
				   ! parameters in abs.inc, rga.inc,
				   ! del.inc
	parameter (pqup=1)


	integer sret_err	! Sign to return the control from current
		! subroutine to which is called it if error is occured.
		! 1 - to return, 0 - to stop.
		! It is intended for handling with subroutine SHEED.
		! In the case of error it can return the control instead of
		! stop. But not for every possible errors return is done.
		! Some of the most original errors could lead to stop.
		! When working with HEED program, sret_err must be zero.
	integer s_err	! Sign of error.
		! 1 - error, 0 - no error

	character*9  TaskName	   ! Name of task, using for generating
				   ! file names.
	character*40 OutputFile	   ! Name of file with output listing.
				   ! Using only in IniHeed.
*** Common split in character and non-character parts (RV 26/10/2007).
	common / cGoEve /
     +	soo, oo,
     +	qevt,nevt,ninfo,
     +	ssimioni,
     +	sret_err, s_err
        common / cGoEveCHR /
     +	TaskName,
     +	OutputFile

	save / cGoEve /
	save / cGoEveCHR /
*** End of change

c 	include 'shellfi.inc'
	integer pqash		! Max. q. of shells
	parameter (pqash=7)
	integer zato		! Z of atom
	integer qash		! quantity of shells
	real athreshold,aweight	! threshold and weight of shells
	integer pqaener,qaener	! Max. and just q. of shell energy
	parameter (pqaener=500)
	real aener		! Energy
	real aphot		! Photoabsorbtion crossection
			! for this point of energy
	common / cshellfi /
     +		zato,
     +		qash,
     +		athreshold(pqash),aweight(pqash),
     +		qaener(pqash),
     +		aener(pqaener,pqash),aphot(pqaener,pqash)
	save / cshellfi /

	integer i,j

        if(soo.eq.0)return
	write(oo,*)
	write(oo,*)' prishellfi:'
	write(oo,*)' zato=',zato,' qash=',qash
	do i=1,qash
	write(oo,*)' number of shell=',i
	write(oo,*)' aweight=',aweight(i),' athreshold=',athreshold(i),
     +		' qaener=',qaener(i)
	write(oo,*)'   aener           aphot'
	do j=1,qaener(i)
		write(oo,*)aener(j,i),aphot(j,i)
	enddo
	enddo

	end
				
