CDECK  ID>, TCALC.
      SUBROUTINE TCALC(Z,DCZ1,E1,EMAG,TZSTOP1,TZSTOP2,ISOL,IZPLANE)
      IMPLICIT REAL*8 (A-H,O-Z)
       DOUBLE PRECISION CONST1,CONST2,CONST3,CONST4,CONST5
       COMMON/CNSTS1/CONST1,CONST2,CONST3,CONST4,CONST5
       DOUBLE PRECISION ALPHAST,VDST,TSTEP,ZSTEP,TFINAL,ZFINAL
       INTEGER ITFINAL,IPRIM
       COMMON/CION/ALPHAST,VDST,TSTEP,ZSTEP,TFINAL,ZFINAL,ITFINAL,IPRIM
       DOUBLE PRECISION ZPLANE1,ZPLANE2,ZPLANE3,ZPLANE4,ZPLANE5,ZPLANE6,
     -      ZPLANE7,ZPLANE8
       INTEGER IZFINAL
       COMMON/CTCALC/ZPLANE1,ZPLANE2,ZPLANE3,ZPLANE4,ZPLANE5,ZPLANE6,
     -      ZPLANE7,ZPLANE8,IZFINAL
C----------------------------------------------------------------------
C CALCULATE ELAPSED TIME ,TZSTOP1, UNTIL ARRIVAL AT NEXT PLANE ,IZPLANE.
C IF TWO POSITIVE SOLUTIONS SET ISOL=2 AND CALCULATE SECOND SOLUTION
C  TZSTOP2.
C-----------------------------------------------------------------------
      ISOL=1
      A=EMAG*CONST2
      B=SQRT(E1)*CONST3*0.01D0*DCZ1
      B2=B*B
      IF(Z.LT.ZPLANE1) THEN
       IZPLANE=1
       C1=Z-ZPLANE1
       c2=0
       ELSE IF(Z.LT.ZPLANE2) THEN
       IZPLANE=2
       C1=Z-ZPLANE2
       C2=Z-ZPLANE1
       ELSE IF(Z.LT.ZPLANE3) THEN
       IZPLANE=3
       C1=Z-ZPLANE3
       C2=Z-ZPLANE2
       ELSE IF(Z.LT.ZPLANE4) THEN
       IZPLANE=4
       C1=Z-ZPLANE4
       C2=Z-ZPLANE3
       ELSE IF(Z.LT.ZPLANE5) THEN
       IZPLANE=5
       C1=Z-ZPLANE5
       C2=Z-ZPLANE4
       ELSE IF(Z.LT.ZPLANE6) THEN
       IZPLANE=6
       C1=Z-ZPLANE6
       C2=Z-ZPLANE5
       ELSE IF(Z.LT.ZPLANE7) THEN
       IZPLANE=7
       C1=Z-ZPLANE7
       C2=Z-ZPLANE6
       ELSE IF(Z.LT.ZPLANE8) THEN
       IZPLANE=8
       C1=Z-ZPLANE8
       C2=Z-ZPLANE7
       ELSE
       IZPLANE=9
       C1=Z-ZPLANE8-10.0D0*ZSTEP
       C2=Z-ZPLANE8
       ENDIF
C CHECK PLANE IN DRIFT DIRECTION ( ONLY ONE TIME SOLUTION POSITIVE)
      FAC=B2-4.0D0*A*C1
      IF(FAC.LT.0.0D0) THEN
C PASSED FINAL PLANE  (RUNAWAY ELECTRONS)
       TZSTOP1=-99.0D0
       RETURN
      ENDIF
      TSTOP1=(-B+SQRT(B2-4.0D0*A*C1))/(2.0D0*A)
      TSTOP2=(-B-SQRT(B2-4.0D0*A*C1))/(2.0D0*A)
      IF(TSTOP1.LT.TSTOP2) THEN
       IF(TSTOP1.GE.0.0D0)THEN
        TZSTOP1=TSTOP1
       ELSE
        TZSTOP1=TSTOP2
       ENDIF
       IF(IZPLANE.EQ.1) RETURN
      ELSE
       IF(TSTOP2.GE.0.0D0) THEN
        TZSTOP1=TSTOP2
       ELSE
        TZSTOP1=TSTOP1
       ENDIF
       IF(IZPLANE.EQ.1) RETURN
      ENDIF
C CHECK PLANE IN BACKWARD DIRECTION (ONLY IF REAL SOLUTION)
      FAC=B2-4.0D0*A*C2
      IF(FAC.LT.0.0D0) RETURN
      TSTOP1=(-B+SQRT(FAC))/(2.0D0*A)
      TSTOP2=(-B-SQRT(FAC))/(2.0D0*A)
C SOLUTIONS CAN BE EITHER BOTH POSITIVE OR BOTH NEGATIVE
C PICK POSITIVE SOLUTIONS AND ORDER IN TIME SEQUENCE OR
C  RETURN IF NEGATIVE
      IF(TSTOP1.LT.0.0D0) RETURN
C  FOUND BACKWARD SOLUTIONS
      ISOL=2
      IZPLANE=IZPLANE-1
      IF(TSTOP1.LT.TSTOP2) THEN
       TZSTOP1=TSTOP1
       TZSTOP2=TSTOP2
      ELSE
       TZSTOP1=TSTOP2
       TZSTOP2=TSTOP1
      ENDIF
      END
