CDECK  ID>, TOF.
      SUBROUTINE TOF
      IMPLICIT REAL*8 (A-H,O-Z)
       DOUBLE PRECISION ALPHAST,VDST,TSTEP,ZSTEP,TFINAL,ZFINAL
       INTEGER ITFINAL,IPRIM
       COMMON/CION/ALPHAST,VDST,TSTEP,ZSTEP,TFINAL,ZFINAL,ITFINAL,IPRIM
*   Combined /TPLOUT/, /TPLOUTG/, /TPLOUTH/ in a single common.
       DOUBLE PRECISION ETPL,XTPL,YTPL,ZTPL,TTPL,XXTPL,YYTPL,ZZTPL,
     -      YZTPL,XZTPL,XYTPL,VZTPL,VYTPL,VXTPL,ATTOINT,ATTERT,AIOERT
       INTEGER NETPL
       COMMON /TPLOUT/ ETPL(8),XTPL(8),YTPL(8),ZTPL(8),TTPL(8),XXTPL(8),
     -      YYTPL(8),ZZTPL(8),YZTPL(8),XZTPL(8),XYTPL(8),
     -      VZTPL(8),VYTPL(8),VXTPL(8),ATTOINT,ATTERT,AIOERT,NETPL(8)
*   Combined /TOFOUT/, /TOFGOUT/ and /TOFHOUT/ in a single common.
       DOUBLE PRECISION RALPHA,RALPER,TOFENE,TOFENER,TOFWV,TOFWVER,
     -      TOFWVZ,TOFWVZER,TOFWVY,TOFWVYER,TOFWVX,TOFWVXER,
     -      TOFDL,TOFDLER,TOFDT,TOFDTER,TOFWR,TOFWRER,
     -      TOFDZZ,TOFDZZER,TOFDXX,TOFDXXER,TOFDYY,TOFDYYER,
     -      TOFDYZ,TOFDYZER,TOFDXY,TOFDXYER,TOFDXZ,TOFDXZER,
     -      TOFWRZ,TOFWRZER,TOFWRY,TOFWRYER,TOFWRX,TOFWRXER,
     -      RATTOF,RATOFER
       COMMON /TOFHOUT/ RALPHA,RALPER,TOFENE,TOFENER,TOFWV,TOFWVER,
     -      TOFWVZ,TOFWVZER,TOFWVY,TOFWVYER,TOFWVX,TOFWVXER,
     -      TOFDL,TOFDLER,TOFDT,TOFDTER,TOFWR,TOFWRER,
     -      TOFDZZ,TOFDZZER,TOFDXX,TOFDXXER,TOFDYY,TOFDYYER,
     -      TOFDYZ,TOFDYZER,TOFDXY,TOFDXYER,TOFDXZ,TOFDXZER,
     -      TOFWRZ,TOFWRZER,TOFWRY,TOFWRYER,TOFWRX,TOFWRXER,
     -      RATTOF,RATOFER
*   Combined /PTTOF/, /PTTOFG/ and /PTTOFH/ in a single common.
       DOUBLE PRECISION RI,EPT,VZPT,VYPT,VXPT,TTEST
       COMMON /PTTOF/ RI(8),EPT(8),VZPT(8),VYPT(8),VXPT(8),TTEST(8)
*-----------------------------------------------------------------------
*   MAGPAR - Interface parameters for gas mixing with Magboltz.
*   (Last changed on  2/ 3/08.)
*-----------------------------------------------------------------------
       INTEGER MXGNAM
       PARAMETER(MXGNAM=60)
       DOUBLE PRECISION FRAMIX
       LOGICAL LF0PLT,LCSPLT,LGKEEP,LBMCPR
       COMMON /MAGPAR/ FRAMIX(MXGNAM),LF0PLT,LCSPLT,LGKEEP,LBMCPR
       LOGICAL         LINPUT,LCELPR,LCELPL,LWRMRK,LISOCL,LCHGCH,
     -         LDRPLT,LDRPRT,LCLPRT,LCLPLT,LMAPCH,LCNTAM,
     -         LDEBUG,LIDENT,LKEYPL,LRNDMI,LPROPR,LPROF,LGSTOP,LGSIG,
     -         LSYNCH,LINPRD
       INTEGER LUNOUT,JFAIL,JEXMEM
       COMMON /PRTPLT/ LINPUT,LCELPR,LCELPL,LWRMRK,LISOCL,LCHGCH,
     -         LDRPLT,LDRPRT,LCLPRT,LCLPLT,LMAPCH,LCNTAM,
     -         LDEBUG,LIDENT,LKEYPL,LRNDMI,LPROPR,LPROF,LGSTOP,LGSIG,
     -         LSYNCH,LINPRD,LUNOUT,JFAIL,JEXMEM
      DIMENSION DLTF(8),DXTF(8),DYTF(8),WR(8),ANTPL(8)
C----------------------------------------------------------
C CALCULATES TIME OF FLIGHT COEFFICIENTS
C---------------------------------------------
      ANTPL(1)=DBLE(NETPL(1))
      WR(1)=ZTPL(1)/(ANTPL(1)*TSTEP)
      DLTF(1)=((ZZTPL(1)/ANTPL(1))-(ZTPL(1)/ANTPL(1))**2)/(2.0D0*TSTEP)
      DXTF(1)=((XXTPL(1)/ANTPL(1))-(XTPL(1)/ANTPL(1))**2)/(2.0D0*TSTEP)
      DYTF(1)=((YYTPL(1)/ANTPL(1))-(YTPL(1)/ANTPL(1))**2)/(2.0D0*TSTEP)
      DO 10 I=2,ITFINAL
      ANTPL(I)=DBLE(NETPL(I))
      WR(I)=((ZTPL(I)/ANTPL(I))-(ZTPL(I-1)/ANTPL(I-1)))/TSTEP
      DLTF(I)=((ZZTPL(I)/ANTPL(I))-(ZTPL(I)/ANTPL(I))**2-(ZZTPL(I-1)/ANT
     /PL(I-1))+(ZTPL(I-1)/ANTPL(I-1))**2)/(2.0D0*TSTEP)
      DXTF(I)=((XXTPL(I)/ANTPL(I))-(XTPL(I)/ANTPL(I))**2-(XXTPL(I-1)/ANT
     /PL(I-1))+(XTPL(I-1)/ANTPL(I-1))**2)/(2.0D0*TSTEP)
      DYTF(I)=((YYTPL(I)/ANTPL(I))-(YTPL(I)/ANTPL(I))**2-(YYTPL(I-1)/ANT
     /PL(I-1))+(YTPL(I-1)/ANTPL(I-1))**2)/(2.0D0*TSTEP)
  10  CONTINUE
      DO 15 I=1,ITFINAL
      WR(I)=WR(I)*1.0D+09
      DLTF(I)=DLTF(I)*1.0D+16
      DXTF(I)=DXTF(I)*1.0D+16
      DYTF(I)=DYTF(I)*1.0D+16
  15  CONTINUE
      IF(LBMCPR)WRITE(LUNOUT,900) ITFINAL
 900  FORMAT(2(/),' TIME OF FLIGHT RESULTS AT',I2,' SEQUENTIAL TIME PLAN
     /ES',/,' PLANE NO.        DL         DX          DY            WR',
     //)
      DO 20 IPL=1,ITFINAL
      IF(LBMCPR)WRITE(LUNOUT,910)
     -     IPL,DLTF(IPL),DXTF(IPL),DYTF(IPL),WR(IPL)
 910  FORMAT(3X,I3,4X,3F12.1,4X,F8.2)
  20  CONTINUE
      IF(NETPL(1).GT.NETPL(ITFINAL)) THEN
C        NET ATTACHMENT TAKE RESULTS FROM PLANE 2
       TOFENE=EPT(2)
       TOFENER=100.0D0*ABS((EPT(2)-EPT(3))/(2.0D0*EPT(2)))
       TOFWV=VZPT(2)
       TOFWVER=100.0D0*ABS((VZPT(2)-VZPT(3))/(2.0D0*VZPT(2)))
       TOFDL=DLTF(2)
       TOFDLER=100.0D0*ABS((DLTF(2)-DLTF(3))/(2.0D0*DLTF(2)))
       TDT2=(DXTF(2)+DYTF(2))/2.0D0
       TDT3=(DXTF(3)+DYTF(3))/2.0D0
       TOFDT=TDT2
       TOFDTER=100.0D0*ABS((TDT2-TDT3)/(2.0D0*TDT2))
       TOFWR=WR(2)
       TOFWRER=100.0D0*ABS((WR(2)-WR(3))/(2.0D0*WR(2)))
        ANST2=DBLE(NETPL(2))
        ANST3=DBLE(NETPL(3))
        ANST4=ANST3-SQRT(ANST3)
        ANST5=LOG(ANST2/ANST3)
        ANST6=LOG(ANST2/ANST4)
        ANST7=ANST6/ANST5
        ANST8=ANST7-1.0D0
       IF(ATTOINT.EQ.-1.0) THEN
C        NO IONISATION
        RALPHA=0.0D0
        RALPER=0.0D0
        RATTOF=-RI(2)
        RATOFER=100.0D0*SQRT(ANST8**2+ATTERT**2)
       ELSE
        RALPHA=RI(2)/(1.0D0-ATTOINT)
        RALPER=100.0D0*SQRT(ANST8**2+AIOERT**2)
        RATTOF=ATTOINT*RI(2)/(1.0D0-ATTOINT)
        RATOFER=100.0D0*SQRT(ANST8**2+ATTERT**2)
       ENDIF
      ELSE
C NET IONISATION TAKE RESULTS FROM PLANE ITFINAL
       I1=ITFINAL
       I2=ITFINAL-1
       TOFENE=EPT(I1)
       TOFENER=100.0D0*ABS((EPT(I1)-EPT(I2))/(2.0D0*EPT(I1)))
       TOFWV=VZPT(I1)
       TOFWVER=100.0D0*ABS((VZPT(I1)-VZPT(I2))/(2.0D0*VZPT(I1)))
       TOFDL=DLTF(I1)
       TOFDLER=100.0D0*ABS((DLTF(I1)-DLTF(I2))/(2.0D0*DLTF(I1)))
       TDT1=(DXTF(I1)+DYTF(I1))/2.0D0
       TDT2=(DXTF(I2)+DYTF(I2))/2.0D0
       TOFDT=TDT1
       TOFDTER=100.0D0*ABS((TDT1-TDT2)/(2.0D0*TDT1))
       TOFWR=WR(I1)
       TOFWRER=100.0D0*ABS((WR(I1)-WR(I2))/(2.0D0*WR(I1)))
       ATER=ABS((RI(I1)-RI(I2))/(2.0D0*RI(I1)))
       RALPHA=RI(I1)/(1.0D0-ATTOINT)
       RALPER=100.0D0*SQRT(ATER**2+AIOERT**2)
       RATTOF=ATTOINT*RI(I1)/(1.0D0-ATTOINT)
       IF(ATTOINT.NE.0.0D0) THEN
        RATOFER=100.0D0*SQRT(ATER**2+ATTERT**2)
       ELSE
        RATOFER=0.0D0
       ENDIF
      ENDIF
      END
