CDECK  ID>, TPLANE.
      SUBROUTINE TPLANE(T,E1,DCX1,DCY1,DCZ1,AP,BP,EFLD,IPLANE)
      IMPLICIT REAL*8 (A-H,O-Z)
*   Array dimensions.
       integer mxngas
       parameter(mxngas=6)
       DOUBLE PRECISION CONST1,CONST2,CONST3,CONST4,CONST5
       COMMON/CNSTS1/CONST1,CONST2,CONST3,CONST4,CONST5
       DOUBLE PRECISION ALPHAST,VDST,TSTEP,ZSTEP,TFINAL,ZFINAL
       INTEGER ITFINAL,IPRIM
       COMMON/CION/ALPHAST,VDST,TSTEP,ZSTEP,TFINAL,ZFINAL,ITFINAL,IPRIM
*   Adjusted size of ICOLL
       DOUBLE PRECISION TIME,SPEC,TMAX1,AVE,DEN,XID,X,Y,Z,ST
       INTEGER ICOLL,NNULL,ICOLN
       COMMON/OUTPT/TIME(300),ICOLL(5*mxngas),SPEC(2048),TMAX1,
     -      AVE,DEN,XID,X,Y,Z,ST,NNULL,ICOLN(512)
*   Combined /TPLOUT/, /TPLOUTG/, /TPLOUTH/ in a single common.
       DOUBLE PRECISION ETPL,XTPL,YTPL,ZTPL,TTPL,XXTPL,YYTPL,ZZTPL,
     -      YZTPL,XZTPL,XYTPL,VZTPL,VYTPL,VXTPL,ATTOINT,ATTERT,AIOERT
       INTEGER NETPL
       COMMON /TPLOUT/ ETPL(8),XTPL(8),YTPL(8),ZTPL(8),TTPL(8),XXTPL(8),
     -      YYTPL(8),ZZTPL(8),YZTPL(8),XZTPL(8),XYTPL(8),
     -      VZTPL(8),VYTPL(8),VXTPL(8),ATTOINT,ATTERT,AIOERT,NETPL(8)
C-----------------------------------------------------------------------
C STORES POSITION, TIME AND ENERGY AND SUMS REQUIRED
C TO CALCULATE DEVIATIONS AND MEANS AT PLANE =IPLANE
C-----------------------------------------------------------------------
      TIMESP=IPLANE*TSTEP
C CALC TIME LEFT TO ARRIVE AT PLANE
      TIMLFT=TIMESP-ST
      T2LFT=TIMLFT*TIMLFT
      A=AP*TIMLFT
      B=BP*T2LFT
      EPLANE=E1+A+B
      CONST6=SQRT(E1/EPLANE)
C     DCX2=DCX1*CONST6
C     DCY2=DCY1*CONST6
      DCZ2=DCZ1*CONST6+EFLD*TIMLFT*CONST5/SQRT(EPLANE)
      XPLANE=X+DCX1*TIMLFT*SQRT(E1)*CONST3*0.01D0
      YPLANE=Y+DCY1*TIMLFT*SQRT(E1)*CONST3*0.01D0
      ZPLANE=Z+DCZ1*TIMLFT*SQRT(E1)*CONST3*0.01D0+T2LFT*EFLD*CONST2
      VZPLANE=DCZ2*SQRT(EPLANE)*CONST3*0.01D0
      XTPL(IPLANE)=XTPL(IPLANE)+XPLANE
      YTPL(IPLANE)=YTPL(IPLANE)+YPLANE
      ZTPL(IPLANE)=ZTPL(IPLANE)+ZPLANE
      XXTPL(IPLANE)=XXTPL(IPLANE)+XPLANE*XPLANE
      YYTPL(IPLANE)=YYTPL(IPLANE)+YPLANE*YPLANE
      ZZTPL(IPLANE)=ZZTPL(IPLANE)+ZPLANE*ZPLANE
      ETPL(IPLANE)=ETPL(IPLANE)+EPLANE
      TTPL(IPLANE)=TTPL(IPLANE)+ST+TIMLFT
      VZTPL(IPLANE)=VZTPL(IPLANE)+VZPLANE
      NETPL(IPLANE)=NETPL(IPLANE)+1
      END
