CDECK  ID>, SRMPLT.
       SUBROUTINE SRMPLT
*-----------------------------------------------------------------------
*   SRMPLT - Plots the SRIM tables
*   (Last changed on 13/12/06.)
*-----------------------------------------------------------------------
       implicit none
       INTEGER MXWIRE,MXSW,MXLIST,MXCHA,MXGRID,MXMATT,MXPOLE,MX3D,
     -         MXPSTR,
     -         MXPAIR,MXPART,MXFOUR,MXCLUS,
     -         MXLINE,MXEQUT,
     -         MXRECL,MXINCH,MXWORD,MXCHAR,MXNAME,MXLUN,
     -         MXINS,MXREG,MXARG,MXCONS,MXVAR,MXALGE,
     -         MXZERO,MXSTCK,MXFPNT,MXFPAR,MXWKLS,
     -         MXHLEV,MXHLRL,MXSUBT,
     -         MXDLVL,MXILVL,MXDLIN,
     -         MXHIST,MXFRAC,MXBANG,MXBTAB,
     -         MXEXG,MXIOG,MXCSG,
     -         MXORIA,
     -         MXMAT,MXEMAT,MXMDIM,
     -         MXSHOT,MXZPAR,
     -         MXMAP,MXEPS,MXWMAP,MXSOLI,MXSBUF,
     -         MXPLAN,MXPOIN,MXEDGE,
     -         MXMCA
       PARAMETER (MXWIRE=  2000,MXSW  =  200)
       PARAMETER (MXMATT=    10)
       PARAMETER (MX3D  =   100)
       PARAMETER (MXPOLE=    10)
       PARAMETER (MXPSTR=   100)
       PARAMETER (MXLIST=  1000)
       PARAMETER (MXHIST=   200, MXCHA = MXLIST/2)
       PARAMETER (MXGRID=    50)
       PARAMETER (MXNAME=   200, MXLUN =    30)
       PARAMETER (MXCLUS=   500, MXPAIR=  2000, MXPART= 10000)
       PARAMETER (MXLINE=   150, MXEQUT=    50)
       PARAMETER (MXFOUR=    16)
       PARAMETER (MXRECL= 10000)
       PARAMETER (MXINCH=  2000, MXWORD=   200, MXCHAR=MXINCH)
       PARAMETER (MXINS =  1000, MXREG =   500, MXCONS=  -500,
     -            MXVAR =   500, MXALGE=   500, MXARG =   100)
       PARAMETER (MXMAT =   500, MXEMAT=200000, MXMDIM=   10)
       PARAMETER (MXZERO=MXWIRE)
       PARAMETER (MXSTCK=     5)
       PARAMETER (MXFPNT= 20000, MXFPAR=    10)
       PARAMETER (MXWKLS=    10)
       PARAMETER (MXHLEV=     9, MXSUBT=   200, MXHLRL=  860)
       PARAMETER (MXDLVL=    10, MXILVL=    20, MXDLIN= 2500)
       PARAMETER (MXFRAC=    13)
       PARAMETER (MXBANG=    20, MXBTAB=    25)
       PARAMETER (MXEXG =    50, MXIOG =    10, MXCSG =  200)
       PARAMETER (MXORIA=  1000)
       PARAMETER (MXSHOT=    10, MXZPAR=4*MXSHOT+2)
       PARAMETER (MXMAP =350000,MXEPS =   10)
       PARAMETER (MXWMAP=     5)
       PARAMETER (MXSOLI=  1000)
       PARAMETER (MXPLAN= 50000, MXPOIN=100000,MXEDGE=100)
       PARAMETER (MXSBUF= 20000)
       PARAMETER (MXMCA = 50000)
*   The parameter MXNBMC must equal MXGNAM (sequence MAGBPARM) !
       INTEGER MXNBMC
       PARAMETER(MXNBMC=60)
       DOUBLE PRECISION WGT,FPRMAT,
     -      FPROJ,FPROJA,FPROJB,FPROJC,FPROJD,FPROJN,
     -      EPSGX,EPSGY,EPSGZ,
     -      GXMIN,GYMIN,GZMIN,GXMAX,GYMAX,GZMAX,
     -      GXBOX,GYBOX,GZBOX
       REAL PXMIN,PYMIN,PZMIN,PXMAX,PYMAX,PZMAX,
     -      PRTHL,PRPHIL,PRAL,PRBL,PRCL,PROROT,
     -      PRFABS,PRFREF,PRFMIN,PRFMAX,PRFCAL,WLMIN,WLMAX,
     -      XT0,YT0,ZT0,XT1,YT1,ZT1,
     -      TRMASS,TRENER,TRCHAR,TRXDIR,TRYDIR,TRZDIR,TRTH,TRPHI,TRDIST,
     -      TRFLUX,TRELEC,TRNSRM
       INTEGER NLINED,NGRIDX,NGRIDY,ITRTYP,NTRLIN,NTRSAM,INDPOS,NCTRW,
     -      NTRFLX,NINORD,
     -      NCPNAM,NCXLAB,NCYLAB,NCFPRO,IPRMAT,
     -      NPRCOL,ICOL0,ICOLBX,ICOLPL,ICOLST,ICOLW1,ICOLW2,ICOLW3,
     -      ICOLD1,ICOLD2,ICOLD3,ICOLRB,NGBOX,ITFSRM,NTRERR
       LOGICAL LTRMS,LTRDEL,LTRINT,LTREXB,LTRCUT,TRFLAG,LINCAL,
     -      LFULLB,LFULLP,LFULLT,LSPLIT,LSORT,LOUTL,LEPSG,LGSTEP,
     -      LDLSRM,LDTSRM,LTRVVL
       COMMON /PARMS / WGT(MXLIST),FPRMAT(3,3),
     -      FPROJ(3,3),FPROJA,FPROJB,FPROJC,FPROJD,FPROJN,
     -      EPSGX,EPSGY,EPSGZ,
     -      GXMIN,GYMIN,GZMIN,GXMAX,GYMAX,GZMAX,
     -      GXBOX(12),GYBOX(12),GZBOX(12),
     -      PXMIN,PYMIN,PZMIN,PXMAX,PYMAX,PZMAX,
     -      PRTHL,PRPHIL,PRAL,PRBL,PRCL,PROROT,
     -      PRFABS,PRFREF,PRFMIN,PRFMAX,PRFCAL,WLMIN,WLMAX,
     -      XT0,YT0,ZT0,XT1,YT1,ZT1,
     -      TRMASS,TRENER,TRCHAR,TRXDIR,TRYDIR,TRZDIR,TRTH,TRPHI,TRDIST,
     -      TRFLUX,TRELEC,TRNSRM,
     -      INDPOS(11000),IPRMAT(3),NCTRW,NCPNAM,
     -      ITRTYP,NTRLIN,NTRSAM,NTRFLX,ITFSRM,NTRERR(10),
     -      NLINED,NINORD,NGRIDX,NGRIDY,NCXLAB,NCYLAB,NCFPRO,
     -      NPRCOL,ICOL0,ICOLBX,ICOLPL,ICOLST,ICOLW1,ICOLW2,ICOLW3,
     -      ICOLD1,ICOLD2,ICOLD3,ICOLRB,NGBOX,
     -      LTRMS,LTRDEL,LTRINT,LTREXB,LTRCUT,TRFLAG(10),LINCAL,
     -      LFULLB,LFULLP,LFULLT,LSPLIT,LSORT,LOUTL,LEPSG,LGSTEP,
     -      LDLSRM,LDTSRM,LTRVVL
       CHARACTER*80 PARTID,PXLAB,PYLAB,PROLAB
       CHARACTER*10 PNAME
       CHARACTER*5  PRVIEW
       CHARACTER*(MXCHAR) FCNTRW
       COMMON /PARCHR/ PARTID,FCNTRW,PNAME,PXLAB,PYLAB,PROLAB,PRVIEW
       REAL SRMDEN,ESRIM,SRMEM,SRMHD,SRMRNG,SRMDT,SRMDL,WSRIM,FSRIM,
     -      XSRIM,YSRIM,ZSRIM,ECSRIM,EKSRIM
       INTEGER NSRIM,NCSRIM,NESRIM
       COMMON /SRMDAT/
     -      ESRIM(MXLIST),SRMEM(MXLIST),
     -      SRMHD(MXLIST),SRMRNG(MXLIST),SRMDT(MXLIST),SRMDL(MXLIST),
     -      XSRIM(MXCLUS),YSRIM(MXCLUS),ZSRIM(MXCLUS),ECSRIM(MXCLUS),
     -      EKSRIM(MXCLUS),SRMDEN,WSRIM,FSRIM,
     -      NSRIM,NCSRIM,NESRIM(MXCLUS)
       COMPLEX ICONS
       REAL PI,CLOG2,EPS0,ECHARG,EMASS,CLIGHT,MEV2KG,BOLTZ,GRAV
       PARAMETER (PI=3.141592653589793238,
     -      CLOG2=0.693147180559945309417,
     -      ICONS=(0.0,1.0),
     -      EPS0=8.854187817E-14,
     -      ECHARG=1.60217733E-19,
     -      EMASS=9.1093897E-31,
     -      GRAV=9.80665,
     -      CLIGHT=2.99792458E4,
     -      MEV2KG = 1.782661845E-30,
     -      BOLTZ=1.380658E-23)
       LOGICAL         LINPUT,LCELPR,LCELPL,LWRMRK,LISOCL,LCHGCH,
     -         LDRPLT,LDRPRT,LCLPRT,LCLPLT,LMAPCH,LCNTAM,
     -         LDEBUG,LIDENT,LKEYPL,LRNDMI,LPROPR,LPROF,LGSTOP,LGSIG,
     -         LSYNCH,LINPRD
       INTEGER LUNOUT,JFAIL,JEXMEM
       COMMON /PRTPLT/ LINPUT,LCELPR,LCELPL,LWRMRK,LISOCL,LCHGCH,
     -         LDRPLT,LDRPRT,LCLPRT,LCLPLT,LMAPCH,LCNTAM,
     -         LDEBUG,LIDENT,LKEYPL,LRNDMI,LPROPR,LPROF,LGSTOP,LGSIG,
     -         LSYNCH,LINPRD,LUNOUT,JFAIL,JEXMEM
       INTEGER I
       REAL DEPLT(MXLIST),DEMAX,STRMIN,STRMAX
*** Nothing to plot of there are 0 or fewer points.
       IF(NSRIM.LT.1)THEN
            PRINT *,' !!!!!! SRMPLT WARNING : Fewer than 1 point in'//
     -           ' the SRIM table; not plotted.'
            RETURN
       ENDIF
*** Energy loss
       DEMAX=0
       DO 10 I=1,NSRIM
       DEPLT(I)=SRMDEN*(SRMEM(I)+SRMHD(I))
       IF(DEPLT(I).GT.DEMAX)DEMAX=DEPLT(I)
10     CONTINUE
       CALL GRAOPT('LOG-X, LIN-Y')
       CALL GRCART(ESRIM(1),0.0,ESRIM(NSRIM),DEMAX*1.1,
     -      'Energy [MeV]','Energy loss [MeV/cm]',
     -      'SRIM energy loss')
       IF(NSRIM.GT.1)THEN
            CALL GRATTS('FUNCTION-1','POLYLINE')
            CALL GRLINE(NSRIM,ESRIM,DEPLT)
       ELSE
            CALL GRATTS('FUNCTION-1','POLYMARKER')
            CALL GRMARK(NSRIM,ESRIM,DEPLT)
       ENDIF
       DO 20 I=1,NSRIM
       DEPLT(I)=SRMDEN*SRMEM(I)
20     CONTINUE
       IF(NSRIM.GT.1)THEN
            CALL GRATTS('FUNCTION-2','POLYLINE')
            CALL GRLINE(NSRIM,ESRIM,DEPLT)
       ELSE
            CALL GRATTS('FUNCTION-2','POLYMARKER')
            CALL GRMARK(NSRIM,ESRIM,DEPLT)
       ENDIF
       DO 30 I=1,NSRIM
       DEPLT(I)=SRMDEN*SRMHD(I)
30     CONTINUE
       IF(NSRIM.GT.1)THEN
            CALL GRATTS('FUNCTION-3','POLYLINE')
            CALL GRLINE(NSRIM,ESRIM,DEPLT)
       ELSE
            CALL GRATTS('FUNCTION-3','POLYMARKER')
            CALL GRMARK(NSRIM,ESRIM,DEPLT)
       ENDIF
       CALL GRNEXT
       CALL GRALOG('SRIM energy loss table.                 ')
*** Range and straggling
       STRMIN=SRMRNG(1)
       STRMAX=SRMRNG(1)
       DO 110 I=1,NSRIM
       IF(SRMRNG(I).GT.STRMAX)STRMAX=SRMRNG(I)
       IF(SRMDL(I).GT.STRMAX)STRMAX=SRMDL(I)
       IF(SRMDT(I).GT.STRMAX)STRMAX=SRMDT(I)
       IF(SRMRNG(I).LT.STRMIN)STRMIN=SRMRNG(I)
       IF(SRMDL(I).LT.STRMIN)STRMIN=SRMDL(I)
       IF(SRMDT(I).LT.STRMIN)STRMIN=SRMDT(I)
110    CONTINUE
       CALL GRAOPT('LOG-X, LOG-Y')
       CALL GRCART(ESRIM(1),STRMIN*0.9,ESRIM(NSRIM),STRMAX*1.1,
     -      'Energy [MeV]','Range, Straggling [cm]',
     -      'SRIM range and straggling')
       IF(NSRIM.GT.1)THEN
            CALL GRATTS('FUNCTION-1','POLYLINE')
            CALL GRLINE(NSRIM,ESRIM,SRMRNG)
            CALL GRATTS('FUNCTION-2','POLYLINE')
            CALL GRLINE(NSRIM,ESRIM,SRMDL)
            CALL GRATTS('FUNCTION-3','POLYLINE')
            CALL GRLINE(NSRIM,ESRIM,SRMDT)
            CALL GRNEXT
       ELSE
            CALL GRATTS('FUNCTION-1','POLYMARKER')
            CALL GRMARK(NSRIM,ESRIM,SRMRNG)
            CALL GRATTS('FUNCTION-2','POLYMARKER')
            CALL GRMARK(NSRIM,ESRIM,SRMDL)
            CALL GRATTS('FUNCTION-3','POLYMARKER')
            CALL GRMARK(NSRIM,ESRIM,SRMDT)
            CALL GRNEXT
       ENDIF
       CALL GRALOG('SRIM range and straggling tables.       ')
*** Reset options
       CALL GRAOPT('LIN-X, LIN-Y')
       END
