CDECK  ID>, SRMRKS.
       SUBROUTINE SRMRKS(STEP,ESTART,DEEM,DEHD)
*-----------------------------------------------------------------------
*   SRMRKS - Precise energy loss integration over a step.
*   (Last changed on 26/10/07.)
*-----------------------------------------------------------------------
       implicit none
       INTEGER MXWIRE,MXSW,MXLIST,MXCHA,MXGRID,MXMATT,MXPOLE,MX3D,
     -         MXPSTR,
     -         MXPAIR,MXPART,MXFOUR,MXCLUS,
     -         MXLINE,MXEQUT,
     -         MXRECL,MXINCH,MXWORD,MXCHAR,MXNAME,MXLUN,
     -         MXINS,MXREG,MXARG,MXCONS,MXVAR,MXALGE,
     -         MXZERO,MXSTCK,MXFPNT,MXFPAR,MXWKLS,
     -         MXHLEV,MXHLRL,MXSUBT,
     -         MXDLVL,MXILVL,MXDLIN,
     -         MXHIST,MXFRAC,MXBANG,MXBTAB,
     -         MXEXG,MXIOG,MXCSG,
     -         MXORIA,
     -         MXMAT,MXEMAT,MXMDIM,
     -         MXSHOT,MXZPAR,
     -         MXMAP,MXEPS,MXWMAP,MXSOLI,MXSBUF,
     -         MXPLAN,MXPOIN,MXEDGE,
     -         MXMCA
       PARAMETER (MXWIRE=  2000,MXSW  =  200)
       PARAMETER (MXMATT=    10)
       PARAMETER (MX3D  =   100)
       PARAMETER (MXPOLE=    10)
       PARAMETER (MXPSTR=   100)
       PARAMETER (MXLIST=  1000)
       PARAMETER (MXHIST=   200, MXCHA = MXLIST/2)
       PARAMETER (MXGRID=    50)
       PARAMETER (MXNAME=   200, MXLUN =    30)
       PARAMETER (MXCLUS=   500, MXPAIR=  2000, MXPART= 10000)
       PARAMETER (MXLINE=   150, MXEQUT=    50)
       PARAMETER (MXFOUR=    16)
       PARAMETER (MXRECL= 10000)
       PARAMETER (MXINCH=  2000, MXWORD=   200, MXCHAR=MXINCH)
       PARAMETER (MXINS =  1000, MXREG =   500, MXCONS=  -500,
     -            MXVAR =   500, MXALGE=   500, MXARG =   100)
       PARAMETER (MXMAT =   500, MXEMAT=200000, MXMDIM=   10)
       PARAMETER (MXZERO=MXWIRE)
       PARAMETER (MXSTCK=     5)
       PARAMETER (MXFPNT= 20000, MXFPAR=    10)
       PARAMETER (MXWKLS=    10)
       PARAMETER (MXHLEV=     9, MXSUBT=   200, MXHLRL=  860)
       PARAMETER (MXDLVL=    10, MXILVL=    20, MXDLIN= 2500)
       PARAMETER (MXFRAC=    13)
       PARAMETER (MXBANG=    20, MXBTAB=    25)
       PARAMETER (MXEXG =    50, MXIOG =    10, MXCSG =  200)
       PARAMETER (MXORIA=  1000)
       PARAMETER (MXSHOT=    10, MXZPAR=4*MXSHOT+2)
       PARAMETER (MXMAP =350000,MXEPS =   10)
       PARAMETER (MXWMAP=     5)
       PARAMETER (MXSOLI=  1000)
       PARAMETER (MXPLAN= 50000, MXPOIN=100000,MXEDGE=100)
       PARAMETER (MXSBUF= 20000)
       PARAMETER (MXMCA = 50000)
*   The parameter MXNBMC must equal MXGNAM (sequence MAGBPARM) !
       INTEGER MXNBMC
       PARAMETER(MXNBMC=60)
       LOGICAL         LINPUT,LCELPR,LCELPL,LWRMRK,LISOCL,LCHGCH,
     -         LDRPLT,LDRPRT,LCLPRT,LCLPLT,LMAPCH,LCNTAM,
     -         LDEBUG,LIDENT,LKEYPL,LRNDMI,LPROPR,LPROF,LGSTOP,LGSIG,
     -         LSYNCH,LINPRD
       INTEGER LUNOUT,JFAIL,JEXMEM
       COMMON /PRTPLT/ LINPUT,LCELPR,LCELPL,LWRMRK,LISOCL,LCHGCH,
     -         LDRPLT,LDRPRT,LCLPRT,LCLPLT,LMAPCH,LCNTAM,
     -         LDEBUG,LIDENT,LKEYPL,LRNDMI,LPROPR,LPROF,LGSTOP,LGSIG,
     -         LSYNCH,LINPRD,LUNOUT,JFAIL,JEXMEM
       REAL SRMDEN,ESRIM,SRMEM,SRMHD,SRMRNG,SRMDT,SRMDL,WSRIM,FSRIM,
     -      XSRIM,YSRIM,ZSRIM,ECSRIM,EKSRIM
       INTEGER NSRIM,NCSRIM,NESRIM
       COMMON /SRMDAT/
     -      ESRIM(MXLIST),SRMEM(MXLIST),
     -      SRMHD(MXLIST),SRMRNG(MXLIST),SRMDT(MXLIST),SRMDL(MXLIST),
     -      XSRIM(MXCLUS),YSRIM(MXCLUS),ZSRIM(MXCLUS),ECSRIM(MXCLUS),
     -      EKSRIM(MXCLUS),SRMDEN,WSRIM,FSRIM,
     -      NSRIM,NCSRIM,NESRIM(MXCLUS)
       DOUBLE PRECISION WGT,FPRMAT,
     -      FPROJ,FPROJA,FPROJB,FPROJC,FPROJD,FPROJN,
     -      EPSGX,EPSGY,EPSGZ,
     -      GXMIN,GYMIN,GZMIN,GXMAX,GYMAX,GZMAX,
     -      GXBOX,GYBOX,GZBOX
       REAL PXMIN,PYMIN,PZMIN,PXMAX,PYMAX,PZMAX,
     -      PRTHL,PRPHIL,PRAL,PRBL,PRCL,PROROT,
     -      PRFABS,PRFREF,PRFMIN,PRFMAX,PRFCAL,WLMIN,WLMAX,
     -      XT0,YT0,ZT0,XT1,YT1,ZT1,
     -      TRMASS,TRENER,TRCHAR,TRXDIR,TRYDIR,TRZDIR,TRTH,TRPHI,TRDIST,
     -      TRFLUX,TRELEC,TRNSRM
       INTEGER NLINED,NGRIDX,NGRIDY,ITRTYP,NTRLIN,NTRSAM,INDPOS,NCTRW,
     -      NTRFLX,NINORD,
     -      NCPNAM,NCXLAB,NCYLAB,NCFPRO,IPRMAT,
     -      NPRCOL,ICOL0,ICOLBX,ICOLPL,ICOLST,ICOLW1,ICOLW2,ICOLW3,
     -      ICOLD1,ICOLD2,ICOLD3,ICOLRB,NGBOX,ITFSRM,NTRERR
       LOGICAL LTRMS,LTRDEL,LTRINT,LTREXB,LTRCUT,TRFLAG,LINCAL,
     -      LFULLB,LFULLP,LFULLT,LSPLIT,LSORT,LOUTL,LEPSG,LGSTEP,
     -      LDLSRM,LDTSRM,LTRVVL
       COMMON /PARMS / WGT(MXLIST),FPRMAT(3,3),
     -      FPROJ(3,3),FPROJA,FPROJB,FPROJC,FPROJD,FPROJN,
     -      EPSGX,EPSGY,EPSGZ,
     -      GXMIN,GYMIN,GZMIN,GXMAX,GYMAX,GZMAX,
     -      GXBOX(12),GYBOX(12),GZBOX(12),
     -      PXMIN,PYMIN,PZMIN,PXMAX,PYMAX,PZMAX,
     -      PRTHL,PRPHIL,PRAL,PRBL,PRCL,PROROT,
     -      PRFABS,PRFREF,PRFMIN,PRFMAX,PRFCAL,WLMIN,WLMAX,
     -      XT0,YT0,ZT0,XT1,YT1,ZT1,
     -      TRMASS,TRENER,TRCHAR,TRXDIR,TRYDIR,TRZDIR,TRTH,TRPHI,TRDIST,
     -      TRFLUX,TRELEC,TRNSRM,
     -      INDPOS(11000),IPRMAT(3),NCTRW,NCPNAM,
     -      ITRTYP,NTRLIN,NTRSAM,NTRFLX,ITFSRM,NTRERR(10),
     -      NLINED,NINORD,NGRIDX,NGRIDY,NCXLAB,NCYLAB,NCFPRO,
     -      NPRCOL,ICOL0,ICOLBX,ICOLPL,ICOLST,ICOLW1,ICOLW2,ICOLW3,
     -      ICOLD1,ICOLD2,ICOLD3,ICOLRB,NGBOX,
     -      LTRMS,LTRDEL,LTRINT,LTREXB,LTRCUT,TRFLAG(10),LINCAL,
     -      LFULLB,LFULLP,LFULLT,LSPLIT,LSORT,LOUTL,LEPSG,LGSTEP,
     -      LDLSRM,LDTSRM,LTRVVL
       CHARACTER*80 PARTID,PXLAB,PYLAB,PROLAB
       CHARACTER*10 PNAME
       CHARACTER*5  PRVIEW
       CHARACTER*(MXCHAR) FCNTRW
       COMMON /PARCHR/ PARTID,FCNTRW,PNAME,PXLAB,PYLAB,PROLAB,PRVIEW
       REAL STEP,ESTART,DEEM,DEHD,S,EPS,
     -      EM21,HD21,EM22,HD22,E2,
     -      EM41,HD41,EM42,HD42,EM43,HD43,EM44,HD44,E4,
     -      DIVDIF,SRMDEM,SRMDHD
       INTEGER I,ITER,NDIV
       EXTERNAL DIVDIF,SRMDEM,SRMDHD
*** Identification.
       IF(LIDENT)PRINT *,' /// ROUTINE SRMRKS ///'
       IF(LDEBUG)WRITE(LUNOUT,'(''  ++++++ SRMRKS DEBUG   :'',
     -      '' Estart = '',E12.5,'' MeV '',
     -      '', step length = '',E12.5,'' cm.'')') ESTART,STEP
*** Precision
       EPS=1.0E-2
*** Initial settings and return point
       NDIV=1
       ITER=0
10     CONTINUE
       ITER=ITER+1
       E4=ESTART
       E2=ESTART
       DEEM=0
       DEHD=0
*** Compute RK2 and RK4 over the number of sub-divisions
       S=STEP/REAL(NDIV)
       DO 20 I=1,NDIV
**  RK2: Initial point
       EM21=S*SRMDEM(E2)*SRMDEN
       HD21=S*SRMDHD(E2)*SRMDEN
*   Mid-way point
       EM22=S*SRMDEM(E2-(EM21+HD21)/2)*SRMDEN
       HD22=S*SRMDHD(E2-(EM21+HD21)/2)*SRMDEN
**  RK4: Initial point
       EM41=S*SRMDEM(E4)*SRMDEN
       HD41=S*SRMDHD(E4)*SRMDEN
*   Mid-way point
       EM42=S*SRMDEM(E4-(EM41+HD41)/2)*SRMDEN
       HD42=S*SRMDHD(E4-(EM41+HD41)/2)*SRMDEN
*   Second mid-point estimate
       EM43=S*SRMDEM(E4-(EM42+HD42)/2)*SRMDEN
       HD43=S*SRMDHD(E4-(EM42+HD42)/2)*SRMDEN
*   End point estimate
       EM44=S*SRMDEM(E4-(EM43+HD43))*SRMDEN
       HD44=S*SRMDHD(E4-(EM43+HD43))*SRMDEN
*   Store the energy loss terms (according to RK4)
       DEEM=DEEM+EM41/6.0+EM42/3.0+EM43/3.0+EM44/6.0
       DEHD=DEHD+HD41/6.0+HD42/3.0+HD43/3.0+HD44/6.0
*   Trace the RK2 energy
       E2=E2-(EM22+HD22)
*   Store the new energy computed with RK4
       E4=E4-((EM41+HD41)/6.0+(EM42+HD42)/3.0+
     -        (EM43+HD43)/3.0+(EM44+HD44)/6.0)
20     CONTINUE
       IF(LDEBUG)WRITE(LUNOUT,'(''  ++++++ SRMRKS DEBUG   :'',
     -      '' Iteration '',I3,'' with '',I3,'' divisions, losses: ''/
     -      26X,''dE4 = '',E12.5,'', dE2 = '',E12.5,'' MeV''/
     -      26X,''EM4 = '',E12.5,'', HD4 = '',E12.5,'' MeV'')')
     -      ITER,NDIV,ESTART-E2,ESTART-E4,DEEM,DEHD
*   Compare the two estimates
       IF(ABS(E2-E4).GT.EPS*(ABS(E2)+ABS(E4)+ABS(ESTART)))THEN
            IF(ITER.GT.10)THEN
                 PRINT *,' !!!!!! SRMRKS WARNING : No convergence'//
     -                ' achieved integrating energy loss.'
                 NTRERR(5)=NTRERR(5)+1
            ELSE
                 NDIV=NDIV*2
                 GOTO 10
            ENDIF
       ELSE
            IF(LDEBUG)WRITE(LUNOUT,'(''  ++++++ SRMRKS DEBUG   :'',
     -           '' Convergence achieved at eps = '',E10.3)') EPS
       ENDIF
       END
